import type { Question } from '../../../types/question';

export const sachunterrichtKlasse12: Question[] = [
  // === ORIGINAL 12 QUESTIONS (sk12-001 through sk12-012) ===
  { id: 'sk12-001', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Welches Tier gibt Milch?', en: 'Which animal gives milk?' },
    options: [{ value: 'kuh', label: { de: 'Die Kuh', en: 'The cow' } }, { value: 'hund', label: { de: 'Der Hund', en: 'The dog' } }, { value: 'fisch', label: { de: 'Der Fisch', en: 'The fish' } }, { value: 'vogel', label: { de: 'Der Vogel', en: 'The bird' } }],
    correctAnswer: 'kuh' },
  { id: 'sk12-002', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Welches Tier kann fliegen?', en: 'Which animal can fly?' },
    options: [{ value: 'vogel', label: { de: 'Der Vogel', en: 'The bird' } }, { value: 'fisch', label: { de: 'Der Fisch', en: 'The fish' } }, { value: 'hund', label: { de: 'Der Hund', en: 'The dog' } }, { value: 'katze', label: { de: 'Die Katze', en: 'The cat' } }],
    correctAnswer: 'vogel' },
  { id: 'sk12-003', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'seasons',
    prompt: { de: 'In welcher Jahreszeit fällt Schnee?', en: 'In which season does it snow?' },
    options: [{ value: 'winter', label: { de: 'Winter', en: 'Winter' } }, { value: 'sommer', label: { de: 'Sommer', en: 'Summer' } }, { value: 'frühling', label: { de: 'Frühling', en: 'Spring' } }, { value: 'herbst', label: { de: 'Herbst', en: 'Autumn' } }],
    correctAnswer: 'winter' },
  { id: 'sk12-004', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'seasons',
    prompt: { de: 'Wann fallen die Blätter von den Bäumen?', en: 'When do leaves fall from trees?' },
    options: [{ value: 'herbst', label: { de: 'Im Herbst', en: 'In autumn' } }, { value: 'frühling', label: { de: 'Im Frühling', en: 'In spring' } }, { value: 'sommer', label: { de: 'Im Sommer', en: 'In summer' } }, { value: 'winter', label: { de: 'Im Winter', en: 'In winter' } }],
    correctAnswer: 'herbst' },
  { id: 'sk12-005', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Mit welchem Körperteil siehst du?', en: 'With which body part do you see?' },
    options: [{ value: 'augen', label: { de: 'Augen', en: 'Eyes' } }, { value: 'ohren', label: { de: 'Ohren', en: 'Ears' } }, { value: 'nase', label: { de: 'Nase', en: 'Nose' } }, { value: 'mund', label: { de: 'Mund', en: 'Mouth' } }],
    correctAnswer: 'augen' },
  { id: 'sk12-006', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Wie viele Sinne hat der Mensch?', en: 'How many senses do humans have?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '5' },
  { id: 'sk12-007', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'plants',
    prompt: { de: 'Was braucht eine Pflanze zum Wachsen?', en: 'What does a plant need to grow?' },
    options: [{ value: 'wasser', label: { de: 'Wasser und Licht', en: 'Water and light' } }, { value: 'schokolade', label: { de: 'Schokolade', en: 'Chocolate' } }, { value: 'strom', label: { de: 'Strom', en: 'Electricity' } }, { value: 'musik', label: { de: 'Musik', en: 'Music' } }],
    correctAnswer: 'wasser' },
  { id: 'sk12-008', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'weather',
    prompt: { de: 'Was entsteht, wenn es regnet und die Sonne scheint?', en: 'What appears when it rains and the sun shines?' },
    options: [{ value: 'regenbogen', label: { de: 'Ein Regenbogen', en: 'A rainbow' } }, { value: 'schnee', label: { de: 'Schnee', en: 'Snow' } }, { value: 'nebel', label: { de: 'Nebel', en: 'Fog' } }, { value: 'wind', label: { de: 'Wind', en: 'Wind' } }],
    correctAnswer: 'regenbogen' },
  { id: 'sk12-009', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'animals',
    prompt: { de: 'Wo leben Fische?', en: 'Where do fish live?' },
    options: [{ value: 'wasser', label: { de: 'Im Wasser', en: 'In water' } }, { value: 'wald', label: { de: 'Im Wald', en: 'In the forest' } }, { value: 'luft', label: { de: 'In der Luft', en: 'In the air' } }, { value: 'wüste', label: { de: 'In der Wüste', en: 'In the desert' } }],
    correctAnswer: 'wasser' },
  { id: 'sk12-010', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'traffic',
    prompt: { de: 'Bei welcher Ampelfarbe darfst du gehen?', en: 'At which traffic light color can you walk?' },
    options: [{ value: 'grün', label: { de: 'Grün', en: 'Green' } }, { value: 'rot', label: { de: 'Rot', en: 'Red' } }, { value: 'gelb', label: { de: 'Gelb', en: 'Yellow' } }],
    correctAnswer: 'grün' },
  { id: 'sk12-011', type: 'drag_sort', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'seasons',
    prompt: { de: 'Sortiere: Welche Dinge passen zu welcher Jahreszeit?', en: 'Sort: Which things belong to which season?' },
    items: [
      { id: 'schnee', label: { de: 'Schnee', en: 'Snow' } },
      { id: 'blüten', label: { de: 'Blüten', en: 'Blossoms' } },
      { id: 'eis', label: { de: 'Eis essen', en: 'Eating ice cream' } },
      { id: 'blätter', label: { de: 'Bunte Blätter', en: 'Colorful leaves' } },
    ],
    categories: [
      { id: 'winter', label: { de: 'Winter', en: 'Winter' } },
      { id: 'frühling', label: { de: 'Frühling', en: 'Spring' } },
      { id: 'sommer', label: { de: 'Sommer', en: 'Summer' } },
      { id: 'herbst', label: { de: 'Herbst', en: 'Autumn' } },
    ],
    correctMapping: { schnee: 'winter', blüten: 'frühling', eis: 'sommer', blätter: 'herbst' } },
  { id: 'sk12-012', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'food',
    prompt: { de: 'Was ist ein Obst?', en: 'Which is a fruit?' },
    options: [{ value: 'apfel', label: { de: 'Apfel', en: 'Apple' } }, { value: 'kartoffel', label: { de: 'Kartoffel', en: 'Potato' } }, { value: 'brot', label: { de: 'Brot', en: 'Bread' } }, { value: 'käse', label: { de: 'Käse', en: 'Cheese' } }],
    correctAnswer: 'apfel' },

  // === NEW QUESTIONS (sk12-013 through sk12-048) ===

  // --- animals ---
  { id: 'sk12-013', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Welches Tier lebt auf dem Bauernhof?', en: 'Which animal lives on a farm?' },
    options: [{ value: 'schwein', label: { de: 'Das Schwein', en: 'The pig' } }, { value: 'löwe', label: { de: 'Der Löwe', en: 'The lion' } }, { value: 'delfin', label: { de: 'Der Delfin', en: 'The dolphin' } }, { value: 'pinguin', label: { de: 'Der Pinguin', en: 'The penguin' } }],
    correctAnswer: 'schwein' },
  { id: 'sk12-014', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Wie nennt man das Baby einer Kuh?', en: 'What is a baby cow called?' },
    options: [{ value: 'kalb', label: { de: 'Kalb', en: 'Calf' } }, { value: 'fohlen', label: { de: 'Fohlen', en: 'Foal' } }, { value: 'küken', label: { de: 'Küken', en: 'Chick' } }, { value: 'welpe', label: { de: 'Welpe', en: 'Puppy' } }],
    correctAnswer: 'kalb' },
  { id: 'sk12-015', type: 'true_false', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Ein Hund ist ein Haustier.', en: 'A dog is a pet.' },
    correctAnswer: true },
  { id: 'sk12-016', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'animals',
    prompt: { de: 'Wie nennt man das Baby eines Pferdes?', en: 'What is a baby horse called?' },
    options: [{ value: 'fohlen', label: { de: 'Fohlen', en: 'Foal' } }, { value: 'kalb', label: { de: 'Kalb', en: 'Calf' } }, { value: 'lamm', label: { de: 'Lamm', en: 'Lamb' } }, { value: 'ferkel', label: { de: 'Ferkel', en: 'Piglet' } }],
    correctAnswer: 'fohlen' },
  { id: 'sk12-017', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'animals',
    prompt: { de: 'Was frisst ein Eichhörnchen am liebsten?', en: 'What does a squirrel like to eat most?' },
    options: [{ value: 'nüsse', label: { de: 'Nüsse', en: 'Nuts' } }, { value: 'fleisch', label: { de: 'Fleisch', en: 'Meat' } }, { value: 'fisch', label: { de: 'Fisch', en: 'Fish' } }, { value: 'käse', label: { de: 'Käse', en: 'Cheese' } }],
    correctAnswer: 'nüsse' },
  { id: 'sk12-018', type: 'true_false', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Ein Huhn legt Eier.', en: 'A chicken lays eggs.' },
    correctAnswer: true },
  { id: 'sk12-019', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Welches Tier macht "Miau"?', en: 'Which animal says "meow"?' },
    options: [{ value: 'katze', label: { de: 'Die Katze', en: 'The cat' } }, { value: 'hund', label: { de: 'Der Hund', en: 'The dog' } }, { value: 'kuh', label: { de: 'Die Kuh', en: 'The cow' } }, { value: 'schaf', label: { de: 'Das Schaf', en: 'The sheep' } }],
    correctAnswer: 'katze' },

  // --- seasons ---
  { id: 'sk12-020', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'seasons',
    prompt: { de: 'In welcher Jahreszeit blühen die Blumen?', en: 'In which season do flowers bloom?' },
    options: [{ value: 'frühling', label: { de: 'Frühling', en: 'Spring' } }, { value: 'winter', label: { de: 'Winter', en: 'Winter' } }, { value: 'herbst', label: { de: 'Herbst', en: 'Autumn' } }, { value: 'sommer', label: { de: 'Sommer', en: 'Summer' } }],
    correctAnswer: 'frühling' },
  { id: 'sk12-021', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'seasons',
    prompt: { de: 'In welcher Jahreszeit gehen wir am liebsten schwimmen?', en: 'In which season do we most like to go swimming?' },
    options: [{ value: 'sommer', label: { de: 'Sommer', en: 'Summer' } }, { value: 'winter', label: { de: 'Winter', en: 'Winter' } }, { value: 'herbst', label: { de: 'Herbst', en: 'Autumn' } }, { value: 'frühling', label: { de: 'Frühling', en: 'Spring' } }],
    correctAnswer: 'sommer' },
  { id: 'sk12-022', type: 'true_false', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'seasons',
    prompt: { de: 'Im Frühling werden die Tage wieder länger.', en: 'In spring the days get longer again.' },
    correctAnswer: true },
  { id: 'sk12-023', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'seasons',
    prompt: { de: 'Welcher Monat gehört zum Winter?', en: 'Which month belongs to winter?' },
    options: [{ value: 'januar', label: { de: 'Januar', en: 'January' } }, { value: 'mai', label: { de: 'Mai', en: 'May' } }, { value: 'august', label: { de: 'August', en: 'August' } }, { value: 'oktober', label: { de: 'Oktober', en: 'October' } }],
    correctAnswer: 'januar' },

  // --- body ---
  { id: 'sk12-024', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Mit welchem Körperteil hörst du?', en: 'With which body part do you hear?' },
    options: [{ value: 'ohren', label: { de: 'Ohren', en: 'Ears' } }, { value: 'augen', label: { de: 'Augen', en: 'Eyes' } }, { value: 'nase', label: { de: 'Nase', en: 'Nose' } }, { value: 'hände', label: { de: 'Hände', en: 'Hands' } }],
    correctAnswer: 'ohren' },
  { id: 'sk12-025', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Wie viele Finger hat eine Hand?', en: 'How many fingers does one hand have?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '5' },
  { id: 'sk12-026', type: 'true_false', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Mit der Nase kann man riechen.', en: 'You can smell with your nose.' },
    correctAnswer: true },
  { id: 'sk12-027', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'body',
    prompt: { de: 'Welcher Sinn gehört zur Zunge?', en: 'Which sense belongs to the tongue?' },
    options: [{ value: 'schmecken', label: { de: 'Schmecken', en: 'Taste' } }, { value: 'riechen', label: { de: 'Riechen', en: 'Smell' } }, { value: 'hören', label: { de: 'Hören', en: 'Hearing' } }, { value: 'sehen', label: { de: 'Sehen', en: 'Sight' } }],
    correctAnswer: 'schmecken' },
  { id: 'sk12-028', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'body',
    prompt: { de: 'Was ist wichtig, um gesund zu bleiben?', en: 'What is important to stay healthy?' },
    options: [{ value: 'bewegung', label: { de: 'Viel Bewegung', en: 'Lots of exercise' } }, { value: 'fernsehen', label: { de: 'Viel fernsehen', en: 'Lots of TV' } }, { value: 'süßes', label: { de: 'Nur Süßes essen', en: 'Only eat sweets' } }, { value: 'nachtschlafen', label: { de: 'Nie schlafen', en: 'Never sleep' } }],
    correctAnswer: 'bewegung' },

  // --- plants ---
  { id: 'sk12-029', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'plants',
    prompt: { de: 'Wie heißt der Teil der Pflanze unter der Erde?', en: 'What is the part of the plant under the ground called?' },
    options: [{ value: 'wurzel', label: { de: 'Die Wurzel', en: 'The root' } }, { value: 'blüte', label: { de: 'Die Blüte', en: 'The blossom' } }, { value: 'blatt', label: { de: 'Das Blatt', en: 'The leaf' } }, { value: 'stamm', label: { de: 'Der Stamm', en: 'The trunk' } }],
    correctAnswer: 'wurzel' },
  { id: 'sk12-030', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'plants',
    prompt: { de: 'Was hat ein Baum, aber eine Blume nicht?', en: 'What does a tree have that a flower does not?' },
    options: [{ value: 'stamm', label: { de: 'Einen dicken Stamm', en: 'A thick trunk' } }, { value: 'blätter', label: { de: 'Blätter', en: 'Leaves' } }, { value: 'wurzeln', label: { de: 'Wurzeln', en: 'Roots' } }, { value: 'farben', label: { de: 'Farben', en: 'Colors' } }],
    correctAnswer: 'stamm' },
  { id: 'sk12-031', type: 'true_false', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'plants',
    prompt: { de: 'Pflanzen brauchen Sonnenlicht zum Wachsen.', en: 'Plants need sunlight to grow.' },
    correctAnswer: true },
  { id: 'sk12-032', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'plants',
    prompt: { de: 'Welcher Teil der Pflanze ist oft bunt und duftet?', en: 'Which part of the plant is often colorful and fragrant?' },
    options: [{ value: 'blüte', label: { de: 'Die Blüte', en: 'The blossom' } }, { value: 'wurzel', label: { de: 'Die Wurzel', en: 'The root' } }, { value: 'stamm', label: { de: 'Der Stamm', en: 'The trunk' } }, { value: 'samen', label: { de: 'Der Samen', en: 'The seed' } }],
    correctAnswer: 'blüte' },

  // --- weather ---
  { id: 'sk12-033', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'weather',
    prompt: { de: 'Was ziehst du an, wenn es regnet?', en: 'What do you wear when it rains?' },
    options: [{ value: 'regenjacke', label: { de: 'Eine Regenjacke', en: 'A rain jacket' } }, { value: 'badehose', label: { de: 'Eine Badehose', en: 'Swim trunks' } }, { value: 'sonnenhut', label: { de: 'Einen Sonnenhut', en: 'A sun hat' } }, { value: 'sandalen', label: { de: 'Sandalen', en: 'Sandals' } }],
    correctAnswer: 'regenjacke' },
  { id: 'sk12-034', type: 'true_false', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'weather',
    prompt: { de: 'Bei einem Gewitter blitzt und donnert es.', en: 'During a thunderstorm there is lightning and thunder.' },
    correctAnswer: true },
  { id: 'sk12-035', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'weather',
    prompt: { de: 'Was ist Nebel?', en: 'What is fog?' },
    options: [{ value: 'wolke', label: { de: 'Eine Wolke am Boden', en: 'A cloud on the ground' } }, { value: 'regen', label: { de: 'Starker Regen', en: 'Heavy rain' } }, { value: 'wind', label: { de: 'Starker Wind', en: 'Strong wind' } }, { value: 'schnee', label: { de: 'Leichter Schnee', en: 'Light snow' } }],
    correctAnswer: 'wolke' },
  { id: 'sk12-036', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'weather',
    prompt: { de: 'Wie heißen kleine Eiskugeln, die vom Himmel fallen?', en: 'What are the small ice balls called that fall from the sky?' },
    options: [{ value: 'hagel', label: { de: 'Hagel', en: 'Hail' } }, { value: 'schnee', label: { de: 'Schnee', en: 'Snow' } }, { value: 'regen', label: { de: 'Regen', en: 'Rain' } }, { value: 'tau', label: { de: 'Tau', en: 'Dew' } }],
    correctAnswer: 'hagel' },

  // --- food ---
  { id: 'sk12-037', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'food',
    prompt: { de: 'Was ist ein Gemüse?', en: 'Which is a vegetable?' },
    options: [{ value: 'karotte', label: { de: 'Die Karotte', en: 'The carrot' } }, { value: 'banane', label: { de: 'Die Banane', en: 'The banana' } }, { value: 'kuchen', label: { de: 'Der Kuchen', en: 'The cake' } }, { value: 'bonbon', label: { de: 'Das Bonbon', en: 'The candy' } }],
    correctAnswer: 'karotte' },
  { id: 'sk12-038', type: 'true_false', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'food',
    prompt: { de: 'Obst und Gemüse sind gesund.', en: 'Fruits and vegetables are healthy.' },
    correctAnswer: true },
  { id: 'sk12-039', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'food',
    prompt: { de: 'Welches Getränk ist am gesündesten?', en: 'Which drink is the healthiest?' },
    options: [{ value: 'wasser', label: { de: 'Wasser', en: 'Water' } }, { value: 'cola', label: { de: 'Cola', en: 'Cola' } }, { value: 'limonade', label: { de: 'Limonade', en: 'Lemonade' } }, { value: 'kakao', label: { de: 'Kakao', en: 'Cocoa' } }],
    correctAnswer: 'wasser' },

  // --- traffic ---
  { id: 'sk12-040', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'traffic',
    prompt: { de: 'Wo sollst du die Straße überqueren?', en: 'Where should you cross the street?' },
    options: [{ value: 'zebrastreifen', label: { de: 'Am Zebrastreifen', en: 'At the crosswalk' } }, { value: 'überall', label: { de: 'Überall', en: 'Anywhere' } }, { value: 'parkplatz', label: { de: 'Auf dem Parkplatz', en: 'In the parking lot' } }, { value: 'kurve', label: { de: 'In der Kurve', en: 'At a curve' } }],
    correctAnswer: 'zebrastreifen' },
  { id: 'sk12-041', type: 'true_false', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'traffic',
    prompt: { de: 'Beim Fahrradfahren sollte man immer einen Helm tragen.', en: 'You should always wear a helmet when cycling.' },
    correctAnswer: true },
  { id: 'sk12-042', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'traffic',
    prompt: { de: 'Was bedeutet ein rotes Ampellicht?', en: 'What does a red traffic light mean?' },
    options: [{ value: 'stehen', label: { de: 'Stehen bleiben', en: 'Stop' } }, { value: 'gehen', label: { de: 'Gehen', en: 'Go' } }, { value: 'rennen', label: { de: 'Schnell rennen', en: 'Run fast' } }, { value: 'warten', label: { de: 'Langsam gehen', en: 'Walk slowly' } }],
    correctAnswer: 'stehen' },

  // --- time ---
  { id: 'sk12-043', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'time',
    prompt: { de: 'Wie viele Tage hat eine Woche?', en: 'How many days are in a week?' },
    options: [{ value: '7', label: { de: '7', en: '7' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '7' },
  { id: 'sk12-044', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'time',
    prompt: { de: 'Welcher Tag kommt nach Montag?', en: 'Which day comes after Monday?' },
    options: [{ value: 'dienstag', label: { de: 'Dienstag', en: 'Tuesday' } }, { value: 'mittwoch', label: { de: 'Mittwoch', en: 'Wednesday' } }, { value: 'sonntag', label: { de: 'Sonntag', en: 'Sunday' } }, { value: 'freitag', label: { de: 'Freitag', en: 'Friday' } }],
    correctAnswer: 'dienstag' },
  { id: 'sk12-045', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'time',
    prompt: { de: 'Wie viele Monate hat ein Jahr?', en: 'How many months are in a year?' },
    options: [{ value: '12', label: { de: '12', en: '12' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '14', label: { de: '14', en: '14' } }],
    correctAnswer: '12' },

  // --- materials ---
  { id: 'sk12-046', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'materials',
    prompt: { de: 'Aus welchem Material ist ein Fenster?', en: 'What material is a window made of?' },
    options: [{ value: 'glas', label: { de: 'Glas', en: 'Glass' } }, { value: 'holz', label: { de: 'Holz', en: 'Wood' } }, { value: 'stoff', label: { de: 'Stoff', en: 'Fabric' } }, { value: 'papier', label: { de: 'Papier', en: 'Paper' } }],
    correctAnswer: 'glas' },
  { id: 'sk12-047', type: 'drag_sort', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'materials',
    prompt: { de: 'Ordne die Gegenstände dem richtigen Material zu.', en: 'Match the objects to the correct material.' },
    items: [
      { id: 'tisch', label: { de: 'Tisch', en: 'Table' } },
      { id: 'löffel', label: { de: 'Löffel', en: 'Spoon' } },
      { id: 'tshirt', label: { de: 'T-Shirt', en: 'T-Shirt' } },
      { id: 'buch', label: { de: 'Buch', en: 'Book' } },
    ],
    categories: [
      { id: 'holz', label: { de: 'Holz', en: 'Wood' } },
      { id: 'metall', label: { de: 'Metall', en: 'Metal' } },
      { id: 'stoff', label: { de: 'Stoff', en: 'Fabric' } },
      { id: 'papier', label: { de: 'Papier', en: 'Paper' } },
    ],
    correctMapping: { tisch: 'holz', löffel: 'metall', tshirt: 'stoff', buch: 'papier' } },
  { id: 'sk12-048', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'materials',
    prompt: { de: 'Welches Material wird aus Bäumen gemacht?', en: 'Which material is made from trees?' },
    options: [{ value: 'papier', label: { de: 'Papier', en: 'Paper' } }, { value: 'metall', label: { de: 'Metall', en: 'Metal' } }, { value: 'glas', label: { de: 'Glas', en: 'Glass' } }, { value: 'plastik', label: { de: 'Plastik', en: 'Plastic' } }],
    correctAnswer: 'papier' },
];
