import type { Question } from '../../../types/question';

export const sachunterrichtKlasse12: Question[] = [
  { id: 'sk12-001', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Welches Tier gibt Milch?', en: 'Which animal gives milk?' },
    options: [{ value: 'kuh', label: { de: 'Die Kuh', en: 'The cow' } }, { value: 'hund', label: { de: 'Der Hund', en: 'The dog' } }, { value: 'fisch', label: { de: 'Der Fisch', en: 'The fish' } }, { value: 'vogel', label: { de: 'Der Vogel', en: 'The bird' } }],
    correctAnswer: 'kuh' },
  { id: 'sk12-002', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'animals',
    prompt: { de: 'Welches Tier kann fliegen?', en: 'Which animal can fly?' },
    options: [{ value: 'vogel', label: { de: 'Der Vogel', en: 'The bird' } }, { value: 'fisch', label: { de: 'Der Fisch', en: 'The fish' } }, { value: 'hund', label: { de: 'Der Hund', en: 'The dog' } }, { value: 'katze', label: { de: 'Die Katze', en: 'The cat' } }],
    correctAnswer: 'vogel' },
  { id: 'sk12-003', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'seasons',
    prompt: { de: 'In welcher Jahreszeit fällt Schnee?', en: 'In which season does it snow?' },
    options: [{ value: 'winter', label: { de: 'Winter', en: 'Winter' } }, { value: 'sommer', label: { de: 'Sommer', en: 'Summer' } }, { value: 'frühling', label: { de: 'Frühling', en: 'Spring' } }, { value: 'herbst', label: { de: 'Herbst', en: 'Autumn' } }],
    correctAnswer: 'winter' },
  { id: 'sk12-004', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'seasons',
    prompt: { de: 'Wann fallen die Blätter von den Bäumen?', en: 'When do leaves fall from trees?' },
    options: [{ value: 'herbst', label: { de: 'Im Herbst', en: 'In autumn' } }, { value: 'frühling', label: { de: 'Im Frühling', en: 'In spring' } }, { value: 'sommer', label: { de: 'Im Sommer', en: 'In summer' } }, { value: 'winter', label: { de: 'Im Winter', en: 'In winter' } }],
    correctAnswer: 'herbst' },
  { id: 'sk12-005', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Mit welchem Körperteil siehst du?', en: 'With which body part do you see?' },
    options: [{ value: 'augen', label: { de: 'Augen', en: 'Eyes' } }, { value: 'ohren', label: { de: 'Ohren', en: 'Ears' } }, { value: 'nase', label: { de: 'Nase', en: 'Nose' } }, { value: 'mund', label: { de: 'Mund', en: 'Mouth' } }],
    correctAnswer: 'augen' },
  { id: 'sk12-006', type: 'multiple_choice', subject: 'sachunterricht', klasse: 1, difficulty: 1, topic: 'body',
    prompt: { de: 'Wie viele Sinne hat der Mensch?', en: 'How many senses do humans have?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '5' },
  { id: 'sk12-007', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'plants',
    prompt: { de: 'Was braucht eine Pflanze zum Wachsen?', en: 'What does a plant need to grow?' },
    options: [{ value: 'wasser', label: { de: 'Wasser und Licht', en: 'Water and light' } }, { value: 'schokolade', label: { de: 'Schokolade', en: 'Chocolate' } }, { value: 'strom', label: { de: 'Strom', en: 'Electricity' } }, { value: 'musik', label: { de: 'Musik', en: 'Music' } }],
    correctAnswer: 'wasser' },
  { id: 'sk12-008', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'weather',
    prompt: { de: 'Was entsteht, wenn es regnet und die Sonne scheint?', en: 'What appears when it rains and the sun shines?' },
    options: [{ value: 'regenbogen', label: { de: 'Ein Regenbogen', en: 'A rainbow' } }, { value: 'schnee', label: { de: 'Schnee', en: 'Snow' } }, { value: 'nebel', label: { de: 'Nebel', en: 'Fog' } }, { value: 'wind', label: { de: 'Wind', en: 'Wind' } }],
    correctAnswer: 'regenbogen' },
  { id: 'sk12-009', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'animals',
    prompt: { de: 'Wo leben Fische?', en: 'Where do fish live?' },
    options: [{ value: 'wasser', label: { de: 'Im Wasser', en: 'In water' } }, { value: 'wald', label: { de: 'Im Wald', en: 'In the forest' } }, { value: 'luft', label: { de: 'In der Luft', en: 'In the air' } }, { value: 'wüste', label: { de: 'In der Wüste', en: 'In the desert' } }],
    correctAnswer: 'wasser' },
  { id: 'sk12-010', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'traffic',
    prompt: { de: 'Bei welcher Ampelfarbe darfst du gehen?', en: 'At which traffic light color can you walk?' },
    options: [{ value: 'grün', label: { de: 'Grün', en: 'Green' } }, { value: 'rot', label: { de: 'Rot', en: 'Red' } }, { value: 'gelb', label: { de: 'Gelb', en: 'Yellow' } }],
    correctAnswer: 'grün' },
  { id: 'sk12-011', type: 'drag_sort', subject: 'sachunterricht', klasse: 2, difficulty: 2, topic: 'seasons',
    prompt: { de: 'Sortiere: Welche Dinge passen zu welcher Jahreszeit?', en: 'Sort: Which things belong to which season?' },
    items: [
      { id: 'schnee', label: { de: 'Schnee', en: 'Snow' } },
      { id: 'blüten', label: { de: 'Blüten', en: 'Blossoms' } },
      { id: 'eis', label: { de: 'Eis essen', en: 'Eating ice cream' } },
      { id: 'blätter', label: { de: 'Bunte Blätter', en: 'Colorful leaves' } },
    ],
    categories: [
      { id: 'winter', label: { de: 'Winter', en: 'Winter' } },
      { id: 'frühling', label: { de: 'Frühling', en: 'Spring' } },
      { id: 'sommer', label: { de: 'Sommer', en: 'Summer' } },
      { id: 'herbst', label: { de: 'Herbst', en: 'Autumn' } },
    ],
    correctMapping: { schnee: 'winter', blüten: 'frühling', eis: 'sommer', blätter: 'herbst' } },
  { id: 'sk12-012', type: 'multiple_choice', subject: 'sachunterricht', klasse: 2, difficulty: 1, topic: 'food',
    prompt: { de: 'Was ist ein Obst?', en: 'Which is a fruit?' },
    options: [{ value: 'apfel', label: { de: 'Apfel', en: 'Apple' } }, { value: 'kartoffel', label: { de: 'Kartoffel', en: 'Potato' } }, { value: 'brot', label: { de: 'Brot', en: 'Bread' } }, { value: 'käse', label: { de: 'Käse', en: 'Cheese' } }],
    correctAnswer: 'apfel' },
];
