import type { Question } from '../../../types/question';

export const sachunterrichtKlasse34: Question[] = [
  { id: 'sk34-001', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'water_cycle',
    prompt: { de: 'Was passiert mit Wasser, wenn es erwärmt wird?', en: 'What happens to water when it is heated?' },
    options: [{ value: 'verdampft', label: { de: 'Es verdampft', en: 'It evaporates' } }, { value: 'gefriert', label: { de: 'Es gefriert', en: 'It freezes' } }, { value: 'verschwindet', label: { de: 'Es verschwindet', en: 'It disappears' } }, { value: 'wird bunt', label: { de: 'Es wird bunt', en: 'It becomes colorful' } }],
    correctAnswer: 'verdampft' },
  { id: 'sk34-002', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'water_cycle',
    prompt: { de: 'Wie heißen die Wassertropfen, die aus Wolken fallen?', en: 'What are the water drops that fall from clouds called?' },
    options: [{ value: 'regen', label: { de: 'Regen', en: 'Rain' } }, { value: 'tau', label: { de: 'Tau', en: 'Dew' } }, { value: 'nebel', label: { de: 'Nebel', en: 'Fog' } }, { value: 'dampf', label: { de: 'Dampf', en: 'Steam' } }],
    correctAnswer: 'regen' },
  { id: 'sk34-003', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'german_states',
    prompt: { de: 'Was ist die Hauptstadt von Deutschland?', en: 'What is the capital of Germany?' },
    options: [{ value: 'berlin', label: { de: 'Berlin', en: 'Berlin' } }, { value: 'münchen', label: { de: 'München', en: 'Munich' } }, { value: 'hamburg', label: { de: 'Hamburg', en: 'Hamburg' } }, { value: 'köln', label: { de: 'Köln', en: 'Cologne' } }],
    correctAnswer: 'berlin' },
  { id: 'sk34-004', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'german_states',
    prompt: { de: 'Wie viele Bundesländer hat Deutschland?', en: 'How many federal states does Germany have?' },
    options: [{ value: '16', label: { de: '16', en: '16' } }, { value: '12', label: { de: '12', en: '12' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '20', label: { de: '20', en: '20' } }],
    correctAnswer: '16' },
  { id: 'sk34-005', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 1, topic: 'solar_system',
    prompt: { de: 'Welcher Planet ist der Erde am nächsten?', en: 'Which planet is closest to Earth?' },
    options: [{ value: 'venus', label: { de: 'Venus', en: 'Venus' } }, { value: 'mars', label: { de: 'Mars', en: 'Mars' } }, { value: 'jupiter', label: { de: 'Jupiter', en: 'Jupiter' } }, { value: 'merkur', label: { de: 'Merkur', en: 'Mercury' } }],
    correctAnswer: 'venus' },
  { id: 'sk34-006', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'solar_system',
    prompt: { de: 'Wie viele Planeten hat unser Sonnensystem?', en: 'How many planets does our solar system have?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '8' },
  { id: 'sk34-007', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'recycling',
    prompt: { de: 'In welche Tonne kommt eine Bananenschale?', en: 'Which bin does a banana peel go in?' },
    options: [{ value: 'bio', label: { de: 'Biotonne (braun)', en: 'Bio bin (brown)' } }, { value: 'papier', label: { de: 'Papiertonne (blau)', en: 'Paper bin (blue)' } }, { value: 'rest', label: { de: 'Restmüll (grau)', en: 'Residual waste (gray)' } }, { value: 'gelb', label: { de: 'Gelber Sack', en: 'Yellow bag' } }],
    correctAnswer: 'bio' },
  { id: 'sk34-008', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'recycling',
    prompt: { de: 'Wohin kommt eine leere Plastikflasche?', en: 'Where does an empty plastic bottle go?' },
    options: [{ value: 'gelb', label: { de: 'Gelber Sack', en: 'Yellow bag' } }, { value: 'rest', label: { de: 'Restmüll', en: 'Residual waste' } }, { value: 'papier', label: { de: 'Papiertonne', en: 'Paper bin' } }, { value: 'bio', label: { de: 'Biotonne', en: 'Bio bin' } }],
    correctAnswer: 'gelb' },
  { id: 'sk34-009', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'food',
    prompt: { de: 'Welche Lebensmittelgruppe gibt am meisten Energie?', en: 'Which food group gives the most energy?' },
    options: [{ value: 'kohlenhydrate', label: { de: 'Kohlenhydrate (Brot, Nudeln)', en: 'Carbohydrates (bread, pasta)' } }, { value: 'vitamine', label: { de: 'Vitamine (Obst)', en: 'Vitamins (fruit)' } }, { value: 'wasser', label: { de: 'Wasser', en: 'Water' } }, { value: 'salz', label: { de: 'Salz', en: 'Salt' } }],
    correctAnswer: 'kohlenhydrate' },
  { id: 'sk34-010', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'german_states',
    prompt: { de: 'Welches ist das größte Bundesland in Deutschland?', en: 'Which is the largest federal state in Germany?' },
    options: [{ value: 'bayern', label: { de: 'Bayern', en: 'Bavaria' } }, { value: 'nrw', label: { de: 'Nordrhein-Westfalen', en: 'North Rhine-Westphalia' } }, { value: 'niedersachsen', label: { de: 'Niedersachsen', en: 'Lower Saxony' } }, { value: 'hessen', label: { de: 'Hessen', en: 'Hesse' } }],
    correctAnswer: 'bayern' },
  { id: 'sk34-011', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 1, topic: 'solar_system',
    prompt: { de: 'Welcher Planet ist am größten?', en: 'Which planet is the largest?' },
    options: [{ value: 'jupiter', label: { de: 'Jupiter', en: 'Jupiter' } }, { value: 'saturn', label: { de: 'Saturn', en: 'Saturn' } }, { value: 'erde', label: { de: 'Erde', en: 'Earth' } }, { value: 'neptun', label: { de: 'Neptun', en: 'Neptune' } }],
    correctAnswer: 'jupiter' },
  { id: 'sk34-012', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'plants',
    prompt: { de: 'Was ist die grüne Farbe in Pflanzenblättern?', en: 'What is the green color in plant leaves?' },
    options: [{ value: 'chlorophyll', label: { de: 'Chlorophyll', en: 'Chlorophyll' } }, { value: 'zucker', label: { de: 'Zucker', en: 'Sugar' } }, { value: 'wasser', label: { de: 'Wasser', en: 'Water' } }, { value: 'erde', label: { de: 'Erde', en: 'Soil' } }],
    correctAnswer: 'chlorophyll' },
];
