import type { Question } from '../../../types/question';

export const sachunterrichtKlasse34: Question[] = [
  // === ORIGINAL 12 QUESTIONS (sk34-001 through sk34-012) ===
  { id: 'sk34-001', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'water_cycle',
    prompt: { de: 'Was passiert mit Wasser, wenn es erwärmt wird?', en: 'What happens to water when it is heated?' },
    options: [{ value: 'verdampft', label: { de: 'Es verdampft', en: 'It evaporates' } }, { value: 'gefriert', label: { de: 'Es gefriert', en: 'It freezes' } }, { value: 'verschwindet', label: { de: 'Es verschwindet', en: 'It disappears' } }, { value: 'wird bunt', label: { de: 'Es wird bunt', en: 'It becomes colorful' } }],
    correctAnswer: 'verdampft' },
  { id: 'sk34-002', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'water_cycle',
    prompt: { de: 'Wie heißen die Wassertropfen, die aus Wolken fallen?', en: 'What are the water drops that fall from clouds called?' },
    options: [{ value: 'regen', label: { de: 'Regen', en: 'Rain' } }, { value: 'tau', label: { de: 'Tau', en: 'Dew' } }, { value: 'nebel', label: { de: 'Nebel', en: 'Fog' } }, { value: 'dampf', label: { de: 'Dampf', en: 'Steam' } }],
    correctAnswer: 'regen' },
  { id: 'sk34-003', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'german_states',
    prompt: { de: 'Was ist die Hauptstadt von Deutschland?', en: 'What is the capital of Germany?' },
    options: [{ value: 'berlin', label: { de: 'Berlin', en: 'Berlin' } }, { value: 'münchen', label: { de: 'München', en: 'Munich' } }, { value: 'hamburg', label: { de: 'Hamburg', en: 'Hamburg' } }, { value: 'köln', label: { de: 'Köln', en: 'Cologne' } }],
    correctAnswer: 'berlin' },
  { id: 'sk34-004', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'german_states',
    prompt: { de: 'Wie viele Bundesländer hat Deutschland?', en: 'How many federal states does Germany have?' },
    options: [{ value: '16', label: { de: '16', en: '16' } }, { value: '12', label: { de: '12', en: '12' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '20', label: { de: '20', en: '20' } }],
    correctAnswer: '16' },
  { id: 'sk34-005', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 1, topic: 'solar_system',
    prompt: { de: 'Welcher Planet ist der Erde am nächsten?', en: 'Which planet is closest to Earth?' },
    options: [{ value: 'venus', label: { de: 'Venus', en: 'Venus' } }, { value: 'mars', label: { de: 'Mars', en: 'Mars' } }, { value: 'jupiter', label: { de: 'Jupiter', en: 'Jupiter' } }, { value: 'merkur', label: { de: 'Merkur', en: 'Mercury' } }],
    correctAnswer: 'venus' },
  { id: 'sk34-006', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'solar_system',
    prompt: { de: 'Wie viele Planeten hat unser Sonnensystem?', en: 'How many planets does our solar system have?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '8' },
  { id: 'sk34-007', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'recycling',
    prompt: { de: 'In welche Tonne kommt eine Bananenschale?', en: 'Which bin does a banana peel go in?' },
    options: [{ value: 'bio', label: { de: 'Biotonne (braun)', en: 'Bio bin (brown)' } }, { value: 'papier', label: { de: 'Papiertonne (blau)', en: 'Paper bin (blue)' } }, { value: 'rest', label: { de: 'Restmüll (grau)', en: 'Residual waste (gray)' } }, { value: 'gelb', label: { de: 'Gelber Sack', en: 'Yellow bag' } }],
    correctAnswer: 'bio' },
  { id: 'sk34-008', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'recycling',
    prompt: { de: 'Wohin kommt eine leere Plastikflasche?', en: 'Where does an empty plastic bottle go?' },
    options: [{ value: 'gelb', label: { de: 'Gelber Sack', en: 'Yellow bag' } }, { value: 'rest', label: { de: 'Restmüll', en: 'Residual waste' } }, { value: 'papier', label: { de: 'Papiertonne', en: 'Paper bin' } }, { value: 'bio', label: { de: 'Biotonne', en: 'Bio bin' } }],
    correctAnswer: 'gelb' },
  { id: 'sk34-009', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'food',
    prompt: { de: 'Welche Lebensmittelgruppe gibt am meisten Energie?', en: 'Which food group gives the most energy?' },
    options: [{ value: 'kohlenhydrate', label: { de: 'Kohlenhydrate (Brot, Nudeln)', en: 'Carbohydrates (bread, pasta)' } }, { value: 'vitamine', label: { de: 'Vitamine (Obst)', en: 'Vitamins (fruit)' } }, { value: 'wasser', label: { de: 'Wasser', en: 'Water' } }, { value: 'salz', label: { de: 'Salz', en: 'Salt' } }],
    correctAnswer: 'kohlenhydrate' },
  { id: 'sk34-010', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'german_states',
    prompt: { de: 'Welches ist das größte Bundesland in Deutschland?', en: 'Which is the largest federal state in Germany?' },
    options: [{ value: 'bayern', label: { de: 'Bayern', en: 'Bavaria' } }, { value: 'nrw', label: { de: 'Nordrhein-Westfalen', en: 'North Rhine-Westphalia' } }, { value: 'niedersachsen', label: { de: 'Niedersachsen', en: 'Lower Saxony' } }, { value: 'hessen', label: { de: 'Hessen', en: 'Hesse' } }],
    correctAnswer: 'bayern' },
  { id: 'sk34-011', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 1, topic: 'solar_system',
    prompt: { de: 'Welcher Planet ist am größten?', en: 'Which planet is the largest?' },
    options: [{ value: 'jupiter', label: { de: 'Jupiter', en: 'Jupiter' } }, { value: 'saturn', label: { de: 'Saturn', en: 'Saturn' } }, { value: 'erde', label: { de: 'Erde', en: 'Earth' } }, { value: 'neptun', label: { de: 'Neptun', en: 'Neptune' } }],
    correctAnswer: 'jupiter' },
  { id: 'sk34-012', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'plants',
    prompt: { de: 'Was ist die grüne Farbe in Pflanzenblättern?', en: 'What is the green color in plant leaves?' },
    options: [{ value: 'chlorophyll', label: { de: 'Chlorophyll', en: 'Chlorophyll' } }, { value: 'zucker', label: { de: 'Zucker', en: 'Sugar' } }, { value: 'wasser', label: { de: 'Wasser', en: 'Water' } }, { value: 'erde', label: { de: 'Erde', en: 'Soil' } }],
    correctAnswer: 'chlorophyll' },

  // === NEW QUESTIONS (sk34-013 through sk34-048) ===

  // --- water_cycle ---
  { id: 'sk34-013', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'water_cycle',
    prompt: { de: 'Wie nennt man es, wenn Wasserdampf wieder zu Wasser wird?', en: 'What is it called when water vapor turns back into water?' },
    options: [{ value: 'kondensation', label: { de: 'Kondensation', en: 'Condensation' } }, { value: 'verdunstung', label: { de: 'Verdunstung', en: 'Evaporation' } }, { value: 'schmelzen', label: { de: 'Schmelzen', en: 'Melting' } }, { value: 'gefrieren', label: { de: 'Gefrieren', en: 'Freezing' } }],
    correctAnswer: 'kondensation' },
  { id: 'sk34-014', type: 'true_false', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'water_cycle',
    prompt: { de: 'Wolken bestehen aus winzigen Wassertröpfchen.', en: 'Clouds are made of tiny water droplets.' },
    correctAnswer: true },
  { id: 'sk34-015', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 3, topic: 'water_cycle',
    prompt: { de: 'Was passiert mit Regenwasser, das in den Boden sickert?', en: 'What happens to rainwater that seeps into the ground?' },
    options: [{ value: 'grundwasser', label: { de: 'Es wird zu Grundwasser', en: 'It becomes groundwater' } }, { value: 'verschwindet', label: { de: 'Es verschwindet für immer', en: 'It disappears forever' } }, { value: 'dampf', label: { de: 'Es wird sofort zu Dampf', en: 'It immediately becomes steam' } }, { value: 'eis', label: { de: 'Es wird zu Eis', en: 'It becomes ice' } }],
    correctAnswer: 'grundwasser' },
  { id: 'sk34-016', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'water_cycle',
    prompt: { de: 'Was treibt den Wasserkreislauf an?', en: 'What drives the water cycle?' },
    options: [{ value: 'sonne', label: { de: 'Die Sonne', en: 'The sun' } }, { value: 'mond', label: { de: 'Der Mond', en: 'The moon' } }, { value: 'wind', label: { de: 'Nur der Wind', en: 'Only the wind' } }, { value: 'menschen', label: { de: 'Die Menschen', en: 'Humans' } }],
    correctAnswer: 'sonne' },

  // --- german_states ---
  { id: 'sk34-017', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'german_states',
    prompt: { de: 'Was ist die Hauptstadt von Bayern?', en: 'What is the capital of Bavaria?' },
    options: [{ value: 'münchen', label: { de: 'München', en: 'Munich' } }, { value: 'nürnberg', label: { de: 'Nürnberg', en: 'Nuremberg' } }, { value: 'augsburg', label: { de: 'Augsburg', en: 'Augsburg' } }, { value: 'regensburg', label: { de: 'Regensburg', en: 'Regensburg' } }],
    correctAnswer: 'münchen' },
  { id: 'sk34-018', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'german_states',
    prompt: { de: 'Welcher Fluss fließt durch Hamburg?', en: 'Which river flows through Hamburg?' },
    options: [{ value: 'elbe', label: { de: 'Elbe', en: 'Elbe' } }, { value: 'rhein', label: { de: 'Rhein', en: 'Rhine' } }, { value: 'donau', label: { de: 'Donau', en: 'Danube' } }, { value: 'main', label: { de: 'Main', en: 'Main' } }],
    correctAnswer: 'elbe' },
  { id: 'sk34-019', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'german_states',
    prompt: { de: 'Welches Land grenzt NICHT an Deutschland?', en: 'Which country does NOT border Germany?' },
    options: [{ value: 'spanien', label: { de: 'Spanien', en: 'Spain' } }, { value: 'frankreich', label: { de: 'Frankreich', en: 'France' } }, { value: 'polen', label: { de: 'Polen', en: 'Poland' } }, { value: 'österreich', label: { de: 'Österreich', en: 'Austria' } }],
    correctAnswer: 'spanien' },
  { id: 'sk34-020', type: 'true_false', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'german_states',
    prompt: { de: 'Der Rhein ist der längste Fluss, der durch Deutschland fließt.', en: 'The Rhine is the longest river flowing through Germany.' },
    correctAnswer: true },
  { id: 'sk34-021', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'german_states',
    prompt: { de: 'Was ist die Hauptstadt von Baden-Württemberg?', en: 'What is the capital of Baden-Württemberg?' },
    options: [{ value: 'stuttgart', label: { de: 'Stuttgart', en: 'Stuttgart' } }, { value: 'freiburg', label: { de: 'Freiburg', en: 'Freiburg' } }, { value: 'karlsruhe', label: { de: 'Karlsruhe', en: 'Karlsruhe' } }, { value: 'heidelberg', label: { de: 'Heidelberg', en: 'Heidelberg' } }],
    correctAnswer: 'stuttgart' },

  // --- solar_system ---
  { id: 'sk34-022', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'solar_system',
    prompt: { de: 'Welcher Planet ist der Sonne am nächsten?', en: 'Which planet is closest to the sun?' },
    options: [{ value: 'merkur', label: { de: 'Merkur', en: 'Mercury' } }, { value: 'venus', label: { de: 'Venus', en: 'Venus' } }, { value: 'erde', label: { de: 'Erde', en: 'Earth' } }, { value: 'mars', label: { de: 'Mars', en: 'Mars' } }],
    correctAnswer: 'merkur' },
  { id: 'sk34-023', type: 'true_false', subject: 'sachunterricht', klasse: 4, difficulty: 1, topic: 'solar_system',
    prompt: { de: 'Die Sonne ist ein Stern.', en: 'The sun is a star.' },
    correctAnswer: true },
  { id: 'sk34-024', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'solar_system',
    prompt: { de: 'Warum gibt es Tag und Nacht auf der Erde?', en: 'Why is there day and night on Earth?' },
    options: [{ value: 'rotation', label: { de: 'Weil sich die Erde um sich selbst dreht', en: 'Because the Earth rotates on its axis' } }, { value: 'mond', label: { de: 'Weil der Mond die Sonne verdeckt', en: 'Because the moon blocks the sun' } }, { value: 'sonne_bewegt', label: { de: 'Weil die Sonne sich um die Erde dreht', en: 'Because the sun orbits the Earth' } }, { value: 'wolken', label: { de: 'Weil Wolken die Sonne verdecken', en: 'Because clouds cover the sun' } }],
    correctAnswer: 'rotation' },
  { id: 'sk34-025', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'solar_system',
    prompt: { de: 'Welcher Planet ist für seine Ringe bekannt?', en: 'Which planet is known for its rings?' },
    options: [{ value: 'saturn', label: { de: 'Saturn', en: 'Saturn' } }, { value: 'jupiter', label: { de: 'Jupiter', en: 'Jupiter' } }, { value: 'uranus', label: { de: 'Uranus', en: 'Uranus' } }, { value: 'neptun', label: { de: 'Neptun', en: 'Neptune' } }],
    correctAnswer: 'saturn' },
  { id: 'sk34-026', type: 'drag_sort', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'solar_system',
    prompt: { de: 'Ordne die Planeten: Welche sind innere Planeten, welche äußere?', en: 'Sort the planets: Which are inner planets, which are outer?' },
    items: [
      { id: 'merkur', label: { de: 'Merkur', en: 'Mercury' } },
      { id: 'venus', label: { de: 'Venus', en: 'Venus' } },
      { id: 'jupiter', label: { de: 'Jupiter', en: 'Jupiter' } },
      { id: 'saturn', label: { de: 'Saturn', en: 'Saturn' } },
    ],
    categories: [
      { id: 'inner', label: { de: 'Innere Planeten', en: 'Inner planets' } },
      { id: 'outer', label: { de: 'Äußere Planeten', en: 'Outer planets' } },
    ],
    correctMapping: { merkur: 'inner', venus: 'inner', jupiter: 'outer', saturn: 'outer' } },

  // --- recycling ---
  { id: 'sk34-027', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'recycling',
    prompt: { de: 'In welche Tonne kommt eine alte Zeitung?', en: 'Which bin does an old newspaper go in?' },
    options: [{ value: 'papier', label: { de: 'Papiertonne (blau)', en: 'Paper bin (blue)' } }, { value: 'gelb', label: { de: 'Gelber Sack', en: 'Yellow bag' } }, { value: 'rest', label: { de: 'Restmüll', en: 'Residual waste' } }, { value: 'bio', label: { de: 'Biotonne', en: 'Bio bin' } }],
    correctAnswer: 'papier' },
  { id: 'sk34-028', type: 'true_false', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'recycling',
    prompt: { de: 'Glasflaschen gehören in den Glascontainer.', en: 'Glass bottles belong in the glass container.' },
    correctAnswer: true },
  { id: 'sk34-029', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'recycling',
    prompt: { de: 'Warum ist Mülltrennung wichtig?', en: 'Why is waste separation important?' },
    options: [{ value: 'recycling', label: { de: 'Damit Materialien wiederverwertet werden können', en: 'So materials can be recycled' } }, { value: 'schön', label: { de: 'Damit die Tonnen schön aussehen', en: 'So the bins look nice' } }, { value: 'spaß', label: { de: 'Weil es Spaß macht', en: 'Because it is fun' } }, { value: 'schneller', label: { de: 'Damit die Müllabfuhr schneller ist', en: 'So garbage collection is faster' } }],
    correctAnswer: 'recycling' },
  { id: 'sk34-030', type: 'drag_sort', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'recycling',
    prompt: { de: 'Sortiere den Müll in die richtige Tonne!', en: 'Sort the waste into the correct bin!' },
    items: [
      { id: 'joghurtbecher', label: { de: 'Joghurtbecher', en: 'Yogurt cup' } },
      { id: 'apfelrest', label: { de: 'Apfelrest', en: 'Apple core' } },
      { id: 'karton', label: { de: 'Karton', en: 'Cardboard' } },
      { id: 'kaputte_tasse', label: { de: 'Kaputte Tasse', en: 'Broken cup' } },
    ],
    categories: [
      { id: 'gelb', label: { de: 'Gelber Sack', en: 'Yellow bag' } },
      { id: 'bio', label: { de: 'Biotonne', en: 'Bio bin' } },
      { id: 'papier', label: { de: 'Papiertonne', en: 'Paper bin' } },
      { id: 'rest', label: { de: 'Restmüll', en: 'Residual waste' } },
    ],
    correctMapping: { joghurtbecher: 'gelb', apfelrest: 'bio', karton: 'papier', kaputte_tasse: 'rest' } },

  // --- plants ---
  { id: 'sk34-031', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'plants',
    prompt: { de: 'Was brauchen Pflanzen zum Wachsen?', en: 'What do plants need to grow?' },
    options: [{ value: 'licht_wasser', label: { de: 'Licht, Wasser und Erde', en: 'Light, water and soil' } }, { value: 'nur_wasser', label: { de: 'Nur Wasser', en: 'Only water' } }, { value: 'nur_licht', label: { de: 'Nur Licht', en: 'Only light' } }, { value: 'nur_erde', label: { de: 'Nur Erde', en: 'Only soil' } }],
    correctAnswer: 'licht_wasser' },
  { id: 'sk34-032', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'plants',
    prompt: { de: 'Welcher Baum verliert im Herbst seine Blätter?', en: 'Which tree loses its leaves in autumn?' },
    options: [{ value: 'eiche', label: { de: 'Eiche (Laubbaum)', en: 'Oak (deciduous tree)' } }, { value: 'fichte', label: { de: 'Fichte (Nadelbaum)', en: 'Spruce (coniferous tree)' } }, { value: 'tanne', label: { de: 'Tanne (Nadelbaum)', en: 'Fir (coniferous tree)' } }, { value: 'kiefer', label: { de: 'Kiefer (Nadelbaum)', en: 'Pine (coniferous tree)' } }],
    correctAnswer: 'eiche' },
  { id: 'sk34-033', type: 'true_false', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'plants',
    prompt: { de: 'Nadelbäume behalten ihre Nadeln im Winter.', en: 'Coniferous trees keep their needles in winter.' },
    correctAnswer: true },
  { id: 'sk34-034', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 3, topic: 'plants',
    prompt: { de: 'Was produzieren Pflanzen bei der Fotosynthese?', en: 'What do plants produce during photosynthesis?' },
    options: [{ value: 'sauerstoff', label: { de: 'Sauerstoff', en: 'Oxygen' } }, { value: 'co2', label: { de: 'Kohlendioxid', en: 'Carbon dioxide' } }, { value: 'stickstoff', label: { de: 'Stickstoff', en: 'Nitrogen' } }, { value: 'helium', label: { de: 'Helium', en: 'Helium' } }],
    correctAnswer: 'sauerstoff' },
  { id: 'sk34-035', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'plants',
    prompt: { de: 'Welcher Teil der Blume lockt Bienen an?', en: 'Which part of the flower attracts bees?' },
    options: [{ value: 'blüte', label: { de: 'Die bunte Blüte', en: 'The colorful blossom' } }, { value: 'wurzel', label: { de: 'Die Wurzel', en: 'The root' } }, { value: 'stamm', label: { de: 'Der Stamm', en: 'The stem' } }, { value: 'blatt', label: { de: 'Das Blatt', en: 'The leaf' } }],
    correctAnswer: 'blüte' },

  // --- electricity (klasse 4) ---
  { id: 'sk34-036', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'electricity',
    prompt: { de: 'Was braucht man für einen einfachen Stromkreis?', en: 'What do you need for a simple electric circuit?' },
    options: [{ value: 'batterie_kabel_lampe', label: { de: 'Batterie, Kabel und Lampe', en: 'Battery, wire and lamp' } }, { value: 'nur_batterie', label: { de: 'Nur eine Batterie', en: 'Only a battery' } }, { value: 'nur_kabel', label: { de: 'Nur Kabel', en: 'Only wires' } }, { value: 'nur_lampe', label: { de: 'Nur eine Lampe', en: 'Only a lamp' } }],
    correctAnswer: 'batterie_kabel_lampe' },
  { id: 'sk34-037', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'electricity',
    prompt: { de: 'Welches Material leitet Strom?', en: 'Which material conducts electricity?' },
    options: [{ value: 'metall', label: { de: 'Metall (z.B. Kupfer)', en: 'Metal (e.g. copper)' } }, { value: 'holz', label: { de: 'Holz', en: 'Wood' } }, { value: 'gummi', label: { de: 'Gummi', en: 'Rubber' } }, { value: 'plastik', label: { de: 'Plastik', en: 'Plastic' } }],
    correctAnswer: 'metall' },
  { id: 'sk34-038', type: 'true_false', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'electricity',
    prompt: { de: 'Windräder und Solarzellen erzeugen erneuerbare Energie.', en: 'Wind turbines and solar panels generate renewable energy.' },
    correctAnswer: true },
  { id: 'sk34-039', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'electricity',
    prompt: { de: 'Warum soll man nicht mit nassen Händen an Steckdosen fassen?', en: 'Why should you not touch power outlets with wet hands?' },
    options: [{ value: 'wasser_leitet', label: { de: 'Weil Wasser Strom leitet', en: 'Because water conducts electricity' } }, { value: 'steckdose_kaputt', label: { de: 'Weil die Steckdose kaputt geht', en: 'Because the outlet breaks' } }, { value: 'strom_mag_kein_wasser', label: { de: 'Weil Strom kein Wasser mag', en: 'Because electricity does not like water' } }, { value: 'haende_kalt', label: { de: 'Weil die Hände zu kalt sind', en: 'Because the hands are too cold' } }],
    correctAnswer: 'wasser_leitet' },

  // --- human_body (klasse 4) ---
  { id: 'sk34-040', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'human_body',
    prompt: { de: 'Welches Organ pumpt das Blut durch den Körper?', en: 'Which organ pumps blood through the body?' },
    options: [{ value: 'herz', label: { de: 'Das Herz', en: 'The heart' } }, { value: 'lunge', label: { de: 'Die Lunge', en: 'The lungs' } }, { value: 'gehirn', label: { de: 'Das Gehirn', en: 'The brain' } }, { value: 'magen', label: { de: 'Der Magen', en: 'The stomach' } }],
    correctAnswer: 'herz' },
  { id: 'sk34-041', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'human_body',
    prompt: { de: 'Was passiert mit der Nahrung im Magen?', en: 'What happens to food in the stomach?' },
    options: [{ value: 'zerkleinert', label: { de: 'Sie wird durch Magensäure zerkleinert', en: 'It is broken down by stomach acid' } }, { value: 'sofort_blut', label: { de: 'Sie geht sofort ins Blut', en: 'It goes directly into the blood' } }, { value: 'wieder_hoch', label: { de: 'Sie geht zurück in den Mund', en: 'It goes back to the mouth' } }, { value: 'trocknet', label: { de: 'Sie trocknet aus', en: 'It dries out' } }],
    correctAnswer: 'zerkleinert' },
  { id: 'sk34-042', type: 'true_false', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'human_body',
    prompt: { de: 'Ein erwachsener Mensch hat über 200 Knochen.', en: 'An adult human has over 200 bones.' },
    correctAnswer: true },
  { id: 'sk34-043', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'human_body',
    prompt: { de: 'Welches Organ brauchen wir zum Atmen?', en: 'Which organ do we need for breathing?' },
    options: [{ value: 'lunge', label: { de: 'Die Lunge', en: 'The lungs' } }, { value: 'leber', label: { de: 'Die Leber', en: 'The liver' } }, { value: 'niere', label: { de: 'Die Niere', en: 'The kidney' } }, { value: 'milz', label: { de: 'Die Milz', en: 'The spleen' } }],
    correctAnswer: 'lunge' },

  // --- magnets (klasse 3) ---
  { id: 'sk34-044', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'magnets',
    prompt: { de: 'Was passiert, wenn man zwei Nordpole eines Magneten zusammenbringt?', en: 'What happens when you bring two north poles of a magnet together?' },
    options: [{ value: 'abstoßen', label: { de: 'Sie stoßen sich ab', en: 'They repel each other' } }, { value: 'anziehen', label: { de: 'Sie ziehen sich an', en: 'They attract each other' } }, { value: 'nichts', label: { de: 'Nichts passiert', en: 'Nothing happens' } }, { value: 'explodieren', label: { de: 'Sie explodieren', en: 'They explode' } }],
    correctAnswer: 'abstoßen' },
  { id: 'sk34-045', type: 'true_false', subject: 'sachunterricht', klasse: 3, difficulty: 1, topic: 'magnets',
    prompt: { de: 'Ein Magnet zieht Gegenstände aus Eisen an.', en: 'A magnet attracts objects made of iron.' },
    correctAnswer: true },
  { id: 'sk34-046', type: 'multiple_choice', subject: 'sachunterricht', klasse: 3, difficulty: 2, topic: 'magnets',
    prompt: { de: 'Welches Material wird von einem Magneten NICHT angezogen?', en: 'Which material is NOT attracted by a magnet?' },
    options: [{ value: 'holz', label: { de: 'Holz', en: 'Wood' } }, { value: 'eisen', label: { de: 'Eisen', en: 'Iron' } }, { value: 'stahl', label: { de: 'Stahl', en: 'Steel' } }, { value: 'nickel', label: { de: 'Nickel', en: 'Nickel' } }],
    correctAnswer: 'holz' },

  // --- food (klasse 4) ---
  { id: 'sk34-047', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 2, topic: 'food',
    prompt: { de: 'Welcher Nährstoff hilft beim Aufbau von Muskeln?', en: 'Which nutrient helps build muscles?' },
    options: [{ value: 'eiweiß', label: { de: 'Eiweiß (Protein)', en: 'Protein' } }, { value: 'zucker', label: { de: 'Zucker', en: 'Sugar' } }, { value: 'fett', label: { de: 'Fett', en: 'Fat' } }, { value: 'salz', label: { de: 'Salz', en: 'Salt' } }],
    correctAnswer: 'eiweiß' },
  { id: 'sk34-048', type: 'multiple_choice', subject: 'sachunterricht', klasse: 4, difficulty: 3, topic: 'food',
    prompt: { de: 'Welches Vitamin stärkt unser Immunsystem und steckt in Orangen?', en: 'Which vitamin strengthens our immune system and is found in oranges?' },
    options: [{ value: 'vitamin_c', label: { de: 'Vitamin C', en: 'Vitamin C' } }, { value: 'vitamin_a', label: { de: 'Vitamin A', en: 'Vitamin A' } }, { value: 'vitamin_d', label: { de: 'Vitamin D', en: 'Vitamin D' } }, { value: 'vitamin_k', label: { de: 'Vitamin K', en: 'Vitamin K' } }],
    correctAnswer: 'vitamin_c' },
];
