import type { Question } from '../../../types/question';

export const mathKlasse2: Question[] = [
  { id: 'mk2-001', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 23 + 15?', en: 'What is 23 + 15?' },
    options: [{ value: '38', label: { de: '38', en: '38' } }, { value: '37', label: { de: '37', en: '37' } }, { value: '39', label: { de: '39', en: '39' } }, { value: '35', label: { de: '35', en: '35' } }],
    correctAnswer: '38' },
  { id: 'mk2-002', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 50 - 23?', en: 'What is 50 - 23?' },
    options: [{ value: '27', label: { de: '27', en: '27' } }, { value: '28', label: { de: '28', en: '28' } }, { value: '26', label: { de: '26', en: '26' } }, { value: '33', label: { de: '33', en: '33' } }],
    correctAnswer: '27' },
  { id: 'mk2-003', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 2 × 5?', en: 'What is 2 × 5?' },
    options: [{ value: '10', label: { de: '10', en: '10' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '12', label: { de: '12', en: '12' } }, { value: '8', label: { de: '8', en: '8' } }],
    correctAnswer: '10' },
  { id: 'mk2-004', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 5 × 3?', en: 'What is 5 × 3?' },
    options: [{ value: '15', label: { de: '15', en: '15' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '20', label: { de: '20', en: '20' } }, { value: '8', label: { de: '8', en: '8' } }],
    correctAnswer: '15' },
  { id: 'mk2-005', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 10 × 4?', en: 'What is 10 × 4?' },
    options: [{ value: '40', label: { de: '40', en: '40' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '44', label: { de: '44', en: '44' } }, { value: '30', label: { de: '30', en: '30' } }],
    correctAnswer: '40' },
  { id: 'mk2-006', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 47 + 38?', en: 'What is 47 + 38?' },
    options: [{ value: '85', label: { de: '85', en: '85' } }, { value: '75', label: { de: '75', en: '75' } }, { value: '86', label: { de: '86', en: '86' } }, { value: '84', label: { de: '84', en: '84' } }],
    correctAnswer: '85' },
  { id: 'mk2-007', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'money',
    prompt: { de: 'Wie viel ist 50 Cent + 50 Cent?', en: 'How much is 50 cents + 50 cents?' },
    options: [{ value: '1€', label: { de: '1 Euro', en: '1 Euro' } }, { value: '2€', label: { de: '2 Euro', en: '2 Euros' } }, { value: '50c', label: { de: '50 Cent', en: '50 cents' } }, { value: '1.50€', label: { de: '1,50 Euro', en: '1.50 Euros' } }],
    correctAnswer: '1€' },
  { id: 'mk2-008', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 73 - 45?', en: 'What is 73 - 45?' },
    options: [{ value: '28', label: { de: '28', en: '28' } }, { value: '32', label: { de: '32', en: '32' } }, { value: '38', label: { de: '38', en: '38' } }, { value: '27', label: { de: '27', en: '27' } }],
    correctAnswer: '28' },
  { id: 'mk2-009', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist gerade (even)?', en: 'Which number is even?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '8' },
  { id: 'mk2-010', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 68 + 32?', en: 'What is 68 + 32?' },
    options: [{ value: '100', label: { de: '100', en: '100' } }, { value: '90', label: { de: '90', en: '90' } }, { value: '98', label: { de: '98', en: '98' } }, { value: '102', label: { de: '102', en: '102' } }],
    correctAnswer: '100' },
  { id: 'mk2-011', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 5 × 5?', en: 'What is 5 × 5?' },
    options: [{ value: '25', label: { de: '25', en: '25' } }, { value: '20', label: { de: '20', en: '20' } }, { value: '30', label: { de: '30', en: '30' } }, { value: '15', label: { de: '15', en: '15' } }],
    correctAnswer: '25' },
  { id: 'mk2-012', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 100 - 47?', en: 'What is 100 - 47?' },
    options: [{ value: '53', label: { de: '53', en: '53' } }, { value: '57', label: { de: '57', en: '57' } }, { value: '63', label: { de: '63', en: '63' } }, { value: '43', label: { de: '43', en: '43' } }],
    correctAnswer: '53' },
];
