import type { Question } from '../../../types/question';

export const mathKlasse1: Question[] = [
  { id: 'mk1-001', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 2 + 3?', en: 'What is 2 + 3?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '5', explanation: { de: '2 + 3 = 5', en: '2 + 3 = 5' } },
  { id: 'mk1-002', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 4 + 1?', en: 'What is 4 + 1?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '4', label: { de: '4', en: '4' } }],
    correctAnswer: '5' },
  { id: 'mk1-003', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 6 + 2?', en: 'What is 6 + 2?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '8' },
  { id: 'mk1-004', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 7 - 3?', en: 'What is 7 - 3?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '4' },
  { id: 'mk1-005', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 9 - 4?', en: 'What is 9 - 4?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '5' },
  { id: 'mk1-006', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 8 + 7?', en: 'What is 8 + 7?' },
    options: [{ value: '15', label: { de: '15', en: '15' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '16', label: { de: '16', en: '16' } }, { value: '13', label: { de: '13', en: '13' } }],
    correctAnswer: '15' },
  { id: 'mk1-007', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 9 + 6?', en: 'What is 9 + 6?' },
    options: [{ value: '15', label: { de: '15', en: '15' } }, { value: '16', label: { de: '16', en: '16' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '13', label: { de: '13', en: '13' } }],
    correctAnswer: '15' },
  { id: 'mk1-008', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 15 - 8?', en: 'What is 15 - 8?' },
    options: [{ value: '7', label: { de: '7', en: '7' } }, { value: '8', label: { de: '8', en: '8' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '9', label: { de: '9', en: '9' } }],
    correctAnswer: '7' },
  { id: 'mk1-009', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist größer?', en: 'Which number is bigger?' },
    options: [{ value: '9', label: { de: '9', en: '9' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '9' },
  { id: 'mk1-010', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt nach 7?', en: 'What number comes after 7?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '7', label: { de: '7', en: '7' } }],
    correctAnswer: '8' },
  { id: 'mk1-011', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 5 + 5?', en: 'What is 5 + 5?' },
    options: [{ value: '10', label: { de: '10', en: '10' } }, { value: '11', label: { de: '11', en: '11' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '8', label: { de: '8', en: '8' } }],
    correctAnswer: '10' },
  { id: 'mk1-012', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 11 + 9?', en: 'What is 11 + 9?' },
    options: [{ value: '20', label: { de: '20', en: '20' } }, { value: '19', label: { de: '19', en: '19' } }, { value: '18', label: { de: '18', en: '18' } }, { value: '21', label: { de: '21', en: '21' } }],
    correctAnswer: '20' },
  { id: 'mk1-013', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 20 - 7?', en: 'What is 20 - 7?' },
    options: [{ value: '13', label: { de: '13', en: '13' } }, { value: '12', label: { de: '12', en: '12' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '11', label: { de: '11', en: '11' } }],
    correctAnswer: '13' },
  { id: 'mk1-014', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt vor 5?', en: 'What number comes before 5?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '4' },
  { id: 'mk1-015', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 10 - 6?', en: 'What is 10 - 6?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '4' },

  // --- New questions mk1-016 through mk1-060 ---

  // Addition - difficulty 1 (single digit)
  { id: 'mk1-016', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 3 + 3?', en: 'What is 3 + 3?' },
    options: [{ value: '6', label: { de: '6', en: '6' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '4', label: { de: '4', en: '4' } }],
    correctAnswer: '6', explanation: { de: '3 + 3 = 6', en: '3 + 3 = 6' } },
  { id: 'mk1-017', type: 'number_input', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 1 + 4?', en: 'What is 1 + 4?' },
    correctAnswer: 5, explanation: { de: '1 + 4 = 5', en: '1 + 4 = 5' } },
  { id: 'mk1-018', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 5 + 3?', en: 'What is 5 + 3?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '8' },
  { id: 'mk1-019', type: 'number_input', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 2 + 2?', en: 'What is 2 + 2?' },
    correctAnswer: 4, hint: { de: 'Zähle 2 weiter ab 2.', en: 'Count 2 more from 2.' } },
  { id: 'mk1-020', type: 'true_false', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Ist 3 + 2 = 5?', en: 'Is 3 + 2 = 5?' },
    correctAnswer: true, explanation: { de: 'Ja! 3 + 2 = 5', en: 'Yes! 3 + 2 = 5' } },
  { id: 'mk1-021', type: 'true_false', subject: 'math', klasse: 1, difficulty: 1, topic: 'addition',
    prompt: { de: 'Ist 4 + 3 = 8?', en: 'Is 4 + 3 = 8?' },
    correctAnswer: false, explanation: { de: 'Nein! 4 + 3 = 7, nicht 8.', en: 'No! 4 + 3 = 7, not 8.' } },

  // Addition - difficulty 2 (bridging to teens)
  { id: 'mk1-022', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 7 + 5?', en: 'What is 7 + 5?' },
    options: [{ value: '12', label: { de: '12', en: '12' } }, { value: '11', label: { de: '11', en: '11' } }, { value: '13', label: { de: '13', en: '13' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '12', explanation: { de: '7 + 5 = 12', en: '7 + 5 = 12' } },
  { id: 'mk1-023', type: 'number_input', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 6 + 8?', en: 'What is 6 + 8?' },
    correctAnswer: 14, hint: { de: 'Zähle 8 weiter ab 6.', en: 'Count 8 more from 6.' } },
  { id: 'mk1-024', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 7 + 7?', en: 'What is 7 + 7?' },
    options: [{ value: '14', label: { de: '14', en: '14' } }, { value: '13', label: { de: '13', en: '13' } }, { value: '15', label: { de: '15', en: '15' } }, { value: '12', label: { de: '12', en: '12' } }],
    correctAnswer: '14' },
  { id: 'mk1-025', type: 'number_input', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 6 + 6?', en: 'What is 6 + 6?' },
    correctAnswer: 12, explanation: { de: '6 + 6 = 12. Das ist ein Doppel!', en: '6 + 6 = 12. That is a double!' } },
  { id: 'mk1-026', type: 'true_false', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Ist 8 + 5 = 13?', en: 'Is 8 + 5 = 13?' },
    correctAnswer: true, explanation: { de: 'Ja! 8 + 5 = 13', en: 'Yes! 8 + 5 = 13' } },
  { id: 'mk1-027', type: 'true_false', subject: 'math', klasse: 1, difficulty: 2, topic: 'addition',
    prompt: { de: 'Ist 9 + 8 = 16?', en: 'Is 9 + 8 = 16?' },
    correctAnswer: false, explanation: { de: 'Nein! 9 + 8 = 17, nicht 16.', en: 'No! 9 + 8 = 17, not 16.' } },

  // Addition - difficulty 3 (within 30)
  { id: 'mk1-028', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 14 + 8?', en: 'What is 14 + 8?' },
    options: [{ value: '22', label: { de: '22', en: '22' } }, { value: '21', label: { de: '21', en: '21' } }, { value: '23', label: { de: '23', en: '23' } }, { value: '20', label: { de: '20', en: '20' } }],
    correctAnswer: '22', explanation: { de: '14 + 8 = 22', en: '14 + 8 = 22' } },
  { id: 'mk1-029', type: 'number_input', subject: 'math', klasse: 1, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 13 + 7?', en: 'What is 13 + 7?' },
    correctAnswer: 20, hint: { de: '13 + 7: Zähle 7 weiter ab 13.', en: '13 + 7: Count 7 more from 13.' } },
  { id: 'mk1-030', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 15 + 9?', en: 'What is 15 + 9?' },
    options: [{ value: '24', label: { de: '24', en: '24' } }, { value: '23', label: { de: '23', en: '23' } }, { value: '25', label: { de: '25', en: '25' } }, { value: '22', label: { de: '22', en: '22' } }],
    correctAnswer: '24' },
  { id: 'mk1-031', type: 'number_input', subject: 'math', klasse: 1, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 16 + 6?', en: 'What is 16 + 6?' },
    correctAnswer: 22, explanation: { de: '16 + 6 = 22', en: '16 + 6 = 22' } },

  // Subtraction - difficulty 1 (single digit)
  { id: 'mk1-032', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 8 - 3?', en: 'What is 8 - 3?' },
    options: [{ value: '5', label: { de: '5', en: '5' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '5' },
  { id: 'mk1-033', type: 'number_input', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 6 - 2?', en: 'What is 6 - 2?' },
    correctAnswer: 4, explanation: { de: '6 - 2 = 4', en: '6 - 2 = 4' } },
  { id: 'mk1-034', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 5 - 1?', en: 'What is 5 - 1?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '4' },
  { id: 'mk1-035', type: 'true_false', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Ist 9 - 5 = 4?', en: 'Is 9 - 5 = 4?' },
    correctAnswer: true, explanation: { de: 'Ja! 9 - 5 = 4', en: 'Yes! 9 - 5 = 4' } },
  { id: 'mk1-036', type: 'true_false', subject: 'math', klasse: 1, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Ist 7 - 2 = 4?', en: 'Is 7 - 2 = 4?' },
    correctAnswer: false, explanation: { de: 'Nein! 7 - 2 = 5, nicht 4.', en: 'No! 7 - 2 = 5, not 4.' } },

  // Subtraction - difficulty 2 (from teens)
  { id: 'mk1-037', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 13 - 5?', en: 'What is 13 - 5?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '8', explanation: { de: '13 - 5 = 8', en: '13 - 5 = 8' } },
  { id: 'mk1-038', type: 'number_input', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 14 - 7?', en: 'What is 14 - 7?' },
    correctAnswer: 7, hint: { de: 'Zähle 7 zurück ab 14.', en: 'Count 7 back from 14.' } },
  { id: 'mk1-039', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 16 - 9?', en: 'What is 16 - 9?' },
    options: [{ value: '7', label: { de: '7', en: '7' } }, { value: '8', label: { de: '8', en: '8' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '5', label: { de: '5', en: '5' } }],
    correctAnswer: '7' },
  { id: 'mk1-040', type: 'number_input', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 12 - 4?', en: 'What is 12 - 4?' },
    correctAnswer: 8, explanation: { de: '12 - 4 = 8', en: '12 - 4 = 8' } },
  { id: 'mk1-041', type: 'true_false', subject: 'math', klasse: 1, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Ist 17 - 9 = 8?', en: 'Is 17 - 9 = 8?' },
    correctAnswer: true, explanation: { de: 'Ja! 17 - 9 = 8', en: 'Yes! 17 - 9 = 8' } },

  // Subtraction - difficulty 3 (within 30)
  { id: 'mk1-042', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 25 - 8?', en: 'What is 25 - 8?' },
    options: [{ value: '17', label: { de: '17', en: '17' } }, { value: '16', label: { de: '16', en: '16' } }, { value: '18', label: { de: '18', en: '18' } }, { value: '15', label: { de: '15', en: '15' } }],
    correctAnswer: '17', explanation: { de: '25 - 8 = 17', en: '25 - 8 = 17' } },
  { id: 'mk1-043', type: 'number_input', subject: 'math', klasse: 1, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 22 - 5?', en: 'What is 22 - 5?' },
    correctAnswer: 17, hint: { de: 'Zähle 5 zurück ab 22.', en: 'Count 5 back from 22.' } },
  { id: 'mk1-044', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 19 - 6?', en: 'What is 19 - 6?' },
    options: [{ value: '13', label: { de: '13', en: '13' } }, { value: '12', label: { de: '12', en: '12' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '11', label: { de: '11', en: '11' } }],
    correctAnswer: '13' },
  { id: 'mk1-045', type: 'true_false', subject: 'math', klasse: 1, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Ist 28 - 9 = 19?', en: 'Is 28 - 9 = 19?' },
    correctAnswer: true, explanation: { de: 'Ja! 28 - 9 = 19', en: 'Yes! 28 - 9 = 19' } },

  // Comparison - difficulty 1
  { id: 'mk1-046', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist kleiner?', en: 'Which number is smaller?' },
    options: [{ value: '3', label: { de: '3', en: '3' } }, { value: '7', label: { de: '7', en: '7' } }],
    correctAnswer: '3', explanation: { de: '3 ist kleiner als 7.', en: '3 is smaller than 7.' } },
  { id: 'mk1-047', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist größer?', en: 'Which number is bigger?' },
    options: [{ value: '2', label: { de: '2', en: '2' } }, { value: '8', label: { de: '8', en: '8' } }],
    correctAnswer: '8' },
  { id: 'mk1-048', type: 'true_false', subject: 'math', klasse: 1, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Ist 5 größer als 3?', en: 'Is 5 bigger than 3?' },
    correctAnswer: true, explanation: { de: 'Ja! 5 ist größer als 3.', en: 'Yes! 5 is bigger than 3.' } },
  { id: 'mk1-049', type: 'true_false', subject: 'math', klasse: 1, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Ist 4 größer als 9?', en: 'Is 4 bigger than 9?' },
    correctAnswer: false, explanation: { de: 'Nein! 4 ist kleiner als 9.', en: 'No! 4 is smaller than 9.' } },

  // Comparison - difficulty 2
  { id: 'mk1-050', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist größer?', en: 'Which number is bigger?' },
    options: [{ value: '14', label: { de: '14', en: '14' } }, { value: '11', label: { de: '11', en: '11' } }],
    correctAnswer: '14', explanation: { de: '14 ist größer als 11.', en: '14 is bigger than 11.' } },
  { id: 'mk1-051', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist kleiner?', en: 'Which number is smaller?' },
    options: [{ value: '17', label: { de: '17', en: '17' } }, { value: '12', label: { de: '12', en: '12' } }],
    correctAnswer: '12' },
  { id: 'mk1-052', type: 'true_false', subject: 'math', klasse: 1, difficulty: 2, topic: 'comparison',
    prompt: { de: 'Ist 18 kleiner als 15?', en: 'Is 18 smaller than 15?' },
    correctAnswer: false, explanation: { de: 'Nein! 18 ist größer als 15.', en: 'No! 18 is bigger than 15.' } },

  // Counting - difficulty 1 (what comes before/after)
  { id: 'mk1-053', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 1, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt nach 3?', en: 'What number comes after 3?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '4' },
  { id: 'mk1-054', type: 'number_input', subject: 'math', klasse: 1, difficulty: 1, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt vor 9?', en: 'What number comes before 9?' },
    correctAnswer: 8, explanation: { de: 'Vor der 9 kommt die 8.', en: 'Before 9 comes 8.' } },
  { id: 'mk1-055', type: 'number_input', subject: 'math', klasse: 1, difficulty: 1, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt nach 4?', en: 'What number comes after 4?' },
    correctAnswer: 5 },

  // Counting - difficulty 2 (skip counting by 2s, larger numbers)
  { id: 'mk1-056', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'counting',
    prompt: { de: 'Zähle in 2er-Schritten: 2, 4, 6, ...?', en: 'Count by 2s: 2, 4, 6, ...?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '8', explanation: { de: 'Beim Zählen in 2er-Schritten kommt nach 6 die 8.', en: 'When counting by 2s, after 6 comes 8.' } },
  { id: 'mk1-057', type: 'multiple_choice', subject: 'math', klasse: 1, difficulty: 2, topic: 'counting',
    prompt: { de: 'Zähle in 2er-Schritten: 4, 6, 8, ...?', en: 'Count by 2s: 4, 6, 8, ...?' },
    options: [{ value: '10', label: { de: '10', en: '10' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '11', label: { de: '11', en: '11' } }, { value: '12', label: { de: '12', en: '12' } }],
    correctAnswer: '10', hint: { de: 'Immer 2 dazu zählen!', en: 'Always add 2!' } },
  { id: 'mk1-058', type: 'number_input', subject: 'math', klasse: 1, difficulty: 2, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt nach 14?', en: 'What number comes after 14?' },
    correctAnswer: 15 },
  { id: 'mk1-059', type: 'number_input', subject: 'math', klasse: 1, difficulty: 2, topic: 'counting',
    prompt: { de: 'Welche Zahl kommt vor 20?', en: 'What number comes before 20?' },
    correctAnswer: 19, explanation: { de: 'Vor der 20 kommt die 19.', en: 'Before 20 comes 19.' } },
  { id: 'mk1-060', type: 'true_false', subject: 'math', klasse: 1, difficulty: 2, topic: 'counting',
    prompt: { de: 'Kommt die 12 nach der 11?', en: 'Does 12 come after 11?' },
    correctAnswer: true, explanation: { de: 'Ja! Nach der 11 kommt die 12.', en: 'Yes! After 11 comes 12.' } },
];
