import type { Question } from '../../../types/question';

export const mathKlasse2: Question[] = [
  { id: 'mk2-001', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 23 + 15?', en: 'What is 23 + 15?' },
    options: [{ value: '38', label: { de: '38', en: '38' } }, { value: '37', label: { de: '37', en: '37' } }, { value: '39', label: { de: '39', en: '39' } }, { value: '35', label: { de: '35', en: '35' } }],
    correctAnswer: '38' },
  { id: 'mk2-002', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 50 - 23?', en: 'What is 50 - 23?' },
    options: [{ value: '27', label: { de: '27', en: '27' } }, { value: '28', label: { de: '28', en: '28' } }, { value: '26', label: { de: '26', en: '26' } }, { value: '33', label: { de: '33', en: '33' } }],
    correctAnswer: '27' },
  { id: 'mk2-003', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 2 × 5?', en: 'What is 2 × 5?' },
    options: [{ value: '10', label: { de: '10', en: '10' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '12', label: { de: '12', en: '12' } }, { value: '8', label: { de: '8', en: '8' } }],
    correctAnswer: '10' },
  { id: 'mk2-004', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 5 × 3?', en: 'What is 5 × 3?' },
    options: [{ value: '15', label: { de: '15', en: '15' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '20', label: { de: '20', en: '20' } }, { value: '8', label: { de: '8', en: '8' } }],
    correctAnswer: '15' },
  { id: 'mk2-005', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 10 × 4?', en: 'What is 10 × 4?' },
    options: [{ value: '40', label: { de: '40', en: '40' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '44', label: { de: '44', en: '44' } }, { value: '30', label: { de: '30', en: '30' } }],
    correctAnswer: '40' },
  { id: 'mk2-006', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 47 + 38?', en: 'What is 47 + 38?' },
    options: [{ value: '85', label: { de: '85', en: '85' } }, { value: '75', label: { de: '75', en: '75' } }, { value: '86', label: { de: '86', en: '86' } }, { value: '84', label: { de: '84', en: '84' } }],
    correctAnswer: '85' },
  { id: 'mk2-007', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'money',
    prompt: { de: 'Wie viel ist 50 Cent + 50 Cent?', en: 'How much is 50 cents + 50 cents?' },
    options: [{ value: '1€', label: { de: '1 Euro', en: '1 Euro' } }, { value: '2€', label: { de: '2 Euro', en: '2 Euros' } }, { value: '50c', label: { de: '50 Cent', en: '50 cents' } }, { value: '1.50€', label: { de: '1,50 Euro', en: '1.50 Euros' } }],
    correctAnswer: '1€' },
  { id: 'mk2-008', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 73 - 45?', en: 'What is 73 - 45?' },
    options: [{ value: '28', label: { de: '28', en: '28' } }, { value: '32', label: { de: '32', en: '32' } }, { value: '38', label: { de: '38', en: '38' } }, { value: '27', label: { de: '27', en: '27' } }],
    correctAnswer: '28' },
  { id: 'mk2-009', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist gerade (even)?', en: 'Which number is even?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '8' },
  { id: 'mk2-010', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 68 + 32?', en: 'What is 68 + 32?' },
    options: [{ value: '100', label: { de: '100', en: '100' } }, { value: '90', label: { de: '90', en: '90' } }, { value: '98', label: { de: '98', en: '98' } }, { value: '102', label: { de: '102', en: '102' } }],
    correctAnswer: '100' },
  { id: 'mk2-011', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 5 × 5?', en: 'What is 5 × 5?' },
    options: [{ value: '25', label: { de: '25', en: '25' } }, { value: '20', label: { de: '20', en: '20' } }, { value: '30', label: { de: '30', en: '30' } }, { value: '15', label: { de: '15', en: '15' } }],
    correctAnswer: '25' },
  { id: 'mk2-012', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 100 - 47?', en: 'What is 100 - 47?' },
    options: [{ value: '53', label: { de: '53', en: '53' } }, { value: '57', label: { de: '57', en: '57' } }, { value: '63', label: { de: '63', en: '63' } }, { value: '43', label: { de: '43', en: '43' } }],
    correctAnswer: '53' },

  // --- New questions (mk2-013 through mk2-048) ---

  // Addition
  { id: 'mk2-013', type: 'number_input', subject: 'math', klasse: 2, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 34 + 12?', en: 'What is 34 + 12?' },
    correctAnswer: 46 },
  { id: 'mk2-014', type: 'number_input', subject: 'math', klasse: 2, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 21 + 16?', en: 'What is 21 + 16?' },
    correctAnswer: 37 },
  { id: 'mk2-015', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 56 + 29?', en: 'What is 56 + 29?' },
    options: [{ value: '85', label: { de: '85', en: '85' } }, { value: '75', label: { de: '75', en: '75' } }, { value: '84', label: { de: '84', en: '84' } }, { value: '95', label: { de: '95', en: '95' } }],
    correctAnswer: '85' },
  { id: 'mk2-016', type: 'number_input', subject: 'math', klasse: 2, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 39 + 44?', en: 'What is 39 + 44?' },
    correctAnswer: 83 },
  { id: 'mk2-017', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 57 + 43?', en: 'What is 57 + 43?' },
    options: [{ value: '100', label: { de: '100', en: '100' } }, { value: '90', label: { de: '90', en: '90' } }, { value: '97', label: { de: '97', en: '97' } }, { value: '110', label: { de: '110', en: '110' } }],
    correctAnswer: '100' },
  { id: 'mk2-018', type: 'number_input', subject: 'math', klasse: 2, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 76 + 24?', en: 'What is 76 + 24?' },
    correctAnswer: 100 },

  // Subtraction
  { id: 'mk2-019', type: 'number_input', subject: 'math', klasse: 2, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 40 - 15?', en: 'What is 40 - 15?' },
    correctAnswer: 25 },
  { id: 'mk2-020', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 36 - 14?', en: 'What is 36 - 14?' },
    options: [{ value: '22', label: { de: '22', en: '22' } }, { value: '20', label: { de: '20', en: '20' } }, { value: '24', label: { de: '24', en: '24' } }, { value: '12', label: { de: '12', en: '12' } }],
    correctAnswer: '22' },
  { id: 'mk2-021', type: 'number_input', subject: 'math', klasse: 2, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 82 - 37?', en: 'What is 82 - 37?' },
    correctAnswer: 45 },
  { id: 'mk2-022', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 65 - 28?', en: 'What is 65 - 28?' },
    options: [{ value: '37', label: { de: '37', en: '37' } }, { value: '43', label: { de: '43', en: '43' } }, { value: '33', label: { de: '33', en: '33' } }, { value: '47', label: { de: '47', en: '47' } }],
    correctAnswer: '37' },
  { id: 'mk2-023', type: 'number_input', subject: 'math', klasse: 2, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 91 - 56?', en: 'What is 91 - 56?' },
    correctAnswer: 35 },
  { id: 'mk2-024', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 100 - 63?', en: 'What is 100 - 63?' },
    options: [{ value: '37', label: { de: '37', en: '37' } }, { value: '47', label: { de: '47', en: '47' } }, { value: '33', label: { de: '33', en: '33' } }, { value: '27', label: { de: '27', en: '27' } }],
    correctAnswer: '37' },

  // Multiplication
  { id: 'mk2-025', type: 'number_input', subject: 'math', klasse: 2, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 3 × 4?', en: 'What is 3 × 4?' },
    correctAnswer: 12 },
  { id: 'mk2-026', type: 'true_false', subject: 'math', klasse: 2, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Ist 4 × 2 = 8?', en: 'Is 4 × 2 = 8?' },
    correctAnswer: true },
  { id: 'mk2-027', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 6 × 7?', en: 'What is 6 × 7?' },
    options: [{ value: '42', label: { de: '42', en: '42' } }, { value: '36', label: { de: '36', en: '36' } }, { value: '48', label: { de: '48', en: '48' } }, { value: '35', label: { de: '35', en: '35' } }],
    correctAnswer: '42' },
  { id: 'mk2-028', type: 'number_input', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 8 × 3?', en: 'What is 8 × 3?' },
    correctAnswer: 24 },
  { id: 'mk2-029', type: 'true_false', subject: 'math', klasse: 2, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Ist 7 × 8 = 54?', en: 'Is 7 × 8 = 54?' },
    correctAnswer: false },
  { id: 'mk2-030', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 3, topic: 'multiplication',
    prompt: { de: 'Was ist 9 × 9?', en: 'What is 9 × 9?' },
    options: [{ value: '81', label: { de: '81', en: '81' } }, { value: '72', label: { de: '72', en: '72' } }, { value: '90', label: { de: '90', en: '90' } }, { value: '79', label: { de: '79', en: '79' } }],
    correctAnswer: '81' },
  { id: 'mk2-031', type: 'number_input', subject: 'math', klasse: 2, difficulty: 3, topic: 'multiplication',
    prompt: { de: 'Was ist 7 × 9?', en: 'What is 7 × 9?' },
    correctAnswer: 63 },

  // Money
  { id: 'mk2-032', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'money',
    prompt: { de: 'Wie viel ist 20 Cent + 30 Cent?', en: 'How much is 20 cents + 30 cents?' },
    options: [{ value: '50c', label: { de: '50 Cent', en: '50 cents' } }, { value: '40c', label: { de: '40 Cent', en: '40 cents' } }, { value: '60c', label: { de: '60 Cent', en: '60 cents' } }, { value: '1€', label: { de: '1 Euro', en: '1 Euro' } }],
    correctAnswer: '50c' },
  { id: 'mk2-033', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'money',
    prompt: { de: 'Wie viele Cent sind 1 Euro?', en: 'How many cents are in 1 Euro?' },
    options: [{ value: '100', label: { de: '100 Cent', en: '100 cents' } }, { value: '50', label: { de: '50 Cent', en: '50 cents' } }, { value: '10', label: { de: '10 Cent', en: '10 cents' } }, { value: '200', label: { de: '200 Cent', en: '200 cents' } }],
    correctAnswer: '100' },
  { id: 'mk2-034', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'money',
    prompt: { de: 'Du hast 2 Euro und kaufst etwas für 1 Euro 30 Cent. Wie viel Wechselgeld bekommst du?', en: 'You have 2 Euros and buy something for 1 Euro 30 cents. How much change do you get?' },
    options: [{ value: '70c', label: { de: '70 Cent', en: '70 cents' } }, { value: '30c', label: { de: '30 Cent', en: '30 cents' } }, { value: '1€', label: { de: '1 Euro', en: '1 Euro' } }, { value: '80c', label: { de: '80 Cent', en: '80 cents' } }],
    correctAnswer: '70c' },
  { id: 'mk2-035', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'money',
    prompt: { de: 'Wie viel ist 1 Euro 50 Cent + 50 Cent?', en: 'How much is 1 Euro 50 cents + 50 cents?' },
    options: [{ value: '2€', label: { de: '2 Euro', en: '2 Euros' } }, { value: '1.50€', label: { de: '1,50 Euro', en: '1.50 Euros' } }, { value: '2.50€', label: { de: '2,50 Euro', en: '2.50 Euros' } }, { value: '1€', label: { de: '1 Euro', en: '1 Euro' } }],
    correctAnswer: '2€' },
  { id: 'mk2-036', type: 'true_false', subject: 'math', klasse: 2, difficulty: 1, topic: 'money',
    prompt: { de: 'Sind 2 Euro mehr als 150 Cent?', en: 'Are 2 Euros more than 150 cents?' },
    correctAnswer: true },

  // Comparison
  { id: 'mk2-037', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist ungerade (odd)?', en: 'Which number is odd?' },
    options: [{ value: '9', label: { de: '9', en: '9' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '9' },
  { id: 'mk2-038', type: 'true_false', subject: 'math', klasse: 2, difficulty: 1, topic: 'comparison',
    prompt: { de: 'Ist 45 größer als 54?', en: 'Is 45 greater than 54?' },
    correctAnswer: false },
  { id: 'mk2-039', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist die größte?', en: 'Which number is the largest?' },
    options: [{ value: '89', label: { de: '89', en: '89' } }, { value: '78', label: { de: '78', en: '78' } }, { value: '87', label: { de: '87', en: '87' } }, { value: '79', label: { de: '79', en: '79' } }],
    correctAnswer: '89' },
  { id: 'mk2-040', type: 'true_false', subject: 'math', klasse: 2, difficulty: 2, topic: 'comparison',
    prompt: { de: 'Ist 36 eine gerade Zahl?', en: 'Is 36 an even number?' },
    correctAnswer: true },
  { id: 'mk2-041', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'comparison',
    prompt: { de: 'Welche Zahl ist die kleinste?', en: 'Which number is the smallest?' },
    options: [{ value: '29', label: { de: '29', en: '29' } }, { value: '41', label: { de: '41', en: '41' } }, { value: '32', label: { de: '32', en: '32' } }, { value: '38', label: { de: '38', en: '38' } }],
    correctAnswer: '29' },

  // Division
  { id: 'mk2-042', type: 'number_input', subject: 'math', klasse: 2, difficulty: 1, topic: 'division',
    prompt: { de: 'Was ist 10 ÷ 2?', en: 'What is 10 ÷ 2?' },
    correctAnswer: 5 },
  { id: 'mk2-043', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 1, topic: 'division',
    prompt: { de: 'Was ist 12 ÷ 3?', en: 'What is 12 ÷ 3?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '5', label: { de: '5', en: '5' } }],
    correctAnswer: '4' },
  { id: 'mk2-044', type: 'number_input', subject: 'math', klasse: 2, difficulty: 1, topic: 'division',
    prompt: { de: 'Was ist 20 ÷ 4?', en: 'What is 20 ÷ 4?' },
    correctAnswer: 5 },
  { id: 'mk2-045', type: 'true_false', subject: 'math', klasse: 2, difficulty: 1, topic: 'division',
    prompt: { de: 'Ist 15 ÷ 3 = 5?', en: 'Is 15 ÷ 3 = 5?' },
    correctAnswer: true },
  { id: 'mk2-046', type: 'multiple_choice', subject: 'math', klasse: 2, difficulty: 2, topic: 'division',
    prompt: { de: 'Was ist 42 ÷ 6?', en: 'What is 42 ÷ 6?' },
    options: [{ value: '7', label: { de: '7', en: '7' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '8', label: { de: '8', en: '8' } }, { value: '9', label: { de: '9', en: '9' } }],
    correctAnswer: '7' },
  { id: 'mk2-047', type: 'number_input', subject: 'math', klasse: 2, difficulty: 2, topic: 'division',
    prompt: { de: 'Was ist 56 ÷ 8?', en: 'What is 56 ÷ 8?' },
    correctAnswer: 7 },
  { id: 'mk2-048', type: 'true_false', subject: 'math', klasse: 2, difficulty: 2, topic: 'division',
    prompt: { de: 'Ist 48 ÷ 6 = 9?', en: 'Is 48 ÷ 6 = 9?' },
    correctAnswer: false },
];
