import type { Question } from '../../../types/question';

export const mathKlasse3: Question[] = [
  // === ORIGINAL 12 QUESTIONS (mk3-001 through mk3-012) ===
  { id: 'mk3-001', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 7 × 8?', en: 'What is 7 × 8?' },
    options: [{ value: '56', label: { de: '56', en: '56' } }, { value: '54', label: { de: '54', en: '54' } }, { value: '63', label: { de: '63', en: '63' } }, { value: '48', label: { de: '48', en: '48' } }],
    correctAnswer: '56' },
  { id: 'mk3-002', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 6 × 9?', en: 'What is 6 × 9?' },
    options: [{ value: '54', label: { de: '54', en: '54' } }, { value: '56', label: { de: '56', en: '56' } }, { value: '63', label: { de: '63', en: '63' } }, { value: '45', label: { de: '45', en: '45' } }],
    correctAnswer: '54' },
  { id: 'mk3-003', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'division',
    prompt: { de: 'Was ist 42 ÷ 6?', en: 'What is 42 ÷ 6?' },
    options: [{ value: '7', label: { de: '7', en: '7' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '8', label: { de: '8', en: '8' } }, { value: '9', label: { de: '9', en: '9' } }],
    correctAnswer: '7' },
  { id: 'mk3-004', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'division',
    prompt: { de: 'Was ist 72 ÷ 8?', en: 'What is 72 ÷ 8?' },
    options: [{ value: '9', label: { de: '9', en: '9' } }, { value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '9' },
  { id: 'mk3-005', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 345 + 267?', en: 'What is 345 + 267?' },
    options: [{ value: '612', label: { de: '612', en: '612' } }, { value: '602', label: { de: '602', en: '602' } }, { value: '622', label: { de: '622', en: '622' } }, { value: '512', label: { de: '512', en: '512' } }],
    correctAnswer: '612' },
  { id: 'mk3-006', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 500 - 237?', en: 'What is 500 - 237?' },
    options: [{ value: '263', label: { de: '263', en: '263' } }, { value: '273', label: { de: '273', en: '273' } }, { value: '363', label: { de: '363', en: '363' } }, { value: '253', label: { de: '253', en: '253' } }],
    correctAnswer: '263' },
  { id: 'mk3-007', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 3 × 9?', en: 'What is 3 × 9?' },
    options: [{ value: '27', label: { de: '27', en: '27' } }, { value: '24', label: { de: '24', en: '24' } }, { value: '36', label: { de: '36', en: '36' } }, { value: '21', label: { de: '21', en: '21' } }],
    correctAnswer: '27' },
  { id: 'mk3-008', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 3, topic: 'multiplication',
    prompt: { de: 'Was ist 12 × 11?', en: 'What is 12 × 11?' },
    options: [{ value: '132', label: { de: '132', en: '132' } }, { value: '121', label: { de: '121', en: '121' } }, { value: '144', label: { de: '144', en: '144' } }, { value: '122', label: { de: '122', en: '122' } }],
    correctAnswer: '132' },
  { id: 'mk3-009', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'geometry',
    prompt: { de: 'Wie viele Ecken hat ein Dreieck?', en: 'How many corners does a triangle have?' },
    options: [{ value: '3', label: { de: '3', en: '3' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '2', label: { de: '2', en: '2' } }],
    correctAnswer: '3' },
  { id: 'mk3-010', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'geometry',
    prompt: { de: 'Wie viele Seiten hat ein Sechseck?', en: 'How many sides does a hexagon have?' },
    options: [{ value: '6', label: { de: '6', en: '6' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '8', label: { de: '8', en: '8' } }, { value: '4', label: { de: '4', en: '4' } }],
    correctAnswer: '6' },
  { id: 'mk3-011', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'time',
    prompt: { de: 'Wie viele Minuten hat eine Stunde?', en: 'How many minutes in one hour?' },
    options: [{ value: '60', label: { de: '60', en: '60' } }, { value: '100', label: { de: '100', en: '100' } }, { value: '30', label: { de: '30', en: '30' } }, { value: '45', label: { de: '45', en: '45' } }],
    correctAnswer: '60' },
  { id: 'mk3-012', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 789 + 211?', en: 'What is 789 + 211?' },
    options: [{ value: '1000', label: { de: '1000', en: '1000' } }, { value: '990', label: { de: '990', en: '990' } }, { value: '900', label: { de: '900', en: '900' } }, { value: '1100', label: { de: '1100', en: '1100' } }],
    correctAnswer: '1000' },

  // === NEW QUESTIONS (mk3-013 through mk3-048) ===

  // --- Multiplication ---
  { id: 'mk3-013', type: 'number_input', subject: 'math', klasse: 3, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 8 × 7?', en: 'What is 8 × 7?' },
    correctAnswer: 56 },
  { id: 'mk3-014', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'multiplication',
    prompt: { de: 'Was ist 9 × 5?', en: 'What is 9 × 5?' },
    options: [{ value: '45', label: { de: '45', en: '45' } }, { value: '40', label: { de: '40', en: '40' } }, { value: '50', label: { de: '50', en: '50' } }, { value: '35', label: { de: '35', en: '35' } }],
    correctAnswer: '45' },
  { id: 'mk3-015', type: 'number_input', subject: 'math', klasse: 3, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 8 × 9?', en: 'What is 8 × 9?' },
    correctAnswer: 72 },
  { id: 'mk3-016', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 14 × 5?', en: 'What is 14 × 5?' },
    options: [{ value: '70', label: { de: '70', en: '70' } }, { value: '65', label: { de: '65', en: '65' } }, { value: '75', label: { de: '75', en: '75' } }, { value: '60', label: { de: '60', en: '60' } }],
    correctAnswer: '70' },
  { id: 'mk3-017', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'multiplication',
    prompt: { de: 'Was ist 15 × 6?', en: 'What is 15 × 6?' },
    options: [{ value: '90', label: { de: '90', en: '90' } }, { value: '80', label: { de: '80', en: '80' } }, { value: '96', label: { de: '96', en: '96' } }, { value: '85', label: { de: '85', en: '85' } }],
    correctAnswer: '90' },
  { id: 'mk3-018', type: 'number_input', subject: 'math', klasse: 3, difficulty: 3, topic: 'multiplication',
    prompt: { de: 'Was ist 25 × 4?', en: 'What is 25 × 4?' },
    correctAnswer: 100 },
  { id: 'mk3-019', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 3, topic: 'multiplication',
    prompt: { de: 'Was ist 13 × 7?', en: 'What is 13 × 7?' },
    options: [{ value: '91', label: { de: '91', en: '91' } }, { value: '84', label: { de: '84', en: '84' } }, { value: '97', label: { de: '97', en: '97' } }, { value: '78', label: { de: '78', en: '78' } }],
    correctAnswer: '91' },
  { id: 'mk3-020', type: 'true_false', subject: 'math', klasse: 3, difficulty: 1, topic: 'multiplication',
    prompt: { de: '4 × 6 = 24. Stimmt das?', en: '4 × 6 = 24. Is this correct?' },
    correctAnswer: true },
  { id: 'mk3-021', type: 'true_false', subject: 'math', klasse: 3, difficulty: 2, topic: 'multiplication',
    prompt: { de: '11 × 9 = 101. Stimmt das?', en: '11 × 9 = 101. Is this correct?' },
    correctAnswer: false },

  // --- Division ---
  { id: 'mk3-022', type: 'number_input', subject: 'math', klasse: 3, difficulty: 1, topic: 'division',
    prompt: { de: 'Was ist 36 ÷ 4?', en: 'What is 36 ÷ 4?' },
    correctAnswer: 9 },
  { id: 'mk3-023', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'division',
    prompt: { de: 'Was ist 56 ÷ 7?', en: 'What is 56 ÷ 7?' },
    options: [{ value: '8', label: { de: '8', en: '8' } }, { value: '7', label: { de: '7', en: '7' } }, { value: '9', label: { de: '9', en: '9' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '8' },
  { id: 'mk3-024', type: 'number_input', subject: 'math', klasse: 3, difficulty: 2, topic: 'division',
    prompt: { de: 'Was ist 81 ÷ 9?', en: 'What is 81 ÷ 9?' },
    correctAnswer: 9 },
  { id: 'mk3-025', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'division',
    prompt: { de: 'Was ist 96 ÷ 8?', en: 'What is 96 ÷ 8?' },
    options: [{ value: '12', label: { de: '12', en: '12' } }, { value: '11', label: { de: '11', en: '11' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '13', label: { de: '13', en: '13' } }],
    correctAnswer: '12' },
  { id: 'mk3-026', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 3, topic: 'division',
    prompt: { de: 'Was ist 144 ÷ 12?', en: 'What is 144 ÷ 12?' },
    options: [{ value: '12', label: { de: '12', en: '12' } }, { value: '11', label: { de: '11', en: '11' } }, { value: '14', label: { de: '14', en: '14' } }, { value: '13', label: { de: '13', en: '13' } }],
    correctAnswer: '12' },
  { id: 'mk3-027', type: 'true_false', subject: 'math', klasse: 3, difficulty: 1, topic: 'division',
    prompt: { de: '48 ÷ 6 = 8. Stimmt das?', en: '48 ÷ 6 = 8. Is this correct?' },
    correctAnswer: true },
  { id: 'mk3-028', type: 'true_false', subject: 'math', klasse: 3, difficulty: 3, topic: 'division',
    prompt: { de: '105 ÷ 7 = 14. Stimmt das?', en: '105 ÷ 7 = 14. Is this correct?' },
    correctAnswer: false },

  // --- Addition ---
  { id: 'mk3-029', type: 'number_input', subject: 'math', klasse: 3, difficulty: 1, topic: 'addition',
    prompt: { de: 'Was ist 123 + 456?', en: 'What is 123 + 456?' },
    correctAnswer: 579 },
  { id: 'mk3-030', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 468 + 375?', en: 'What is 468 + 375?' },
    options: [{ value: '843', label: { de: '843', en: '843' } }, { value: '833', label: { de: '833', en: '833' } }, { value: '853', label: { de: '853', en: '853' } }, { value: '743', label: { de: '743', en: '743' } }],
    correctAnswer: '843' },
  { id: 'mk3-031', type: 'number_input', subject: 'math', klasse: 3, difficulty: 2, topic: 'addition',
    prompt: { de: 'Was ist 299 + 301?', en: 'What is 299 + 301?' },
    correctAnswer: 600 },
  { id: 'mk3-032', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 3, topic: 'addition',
    prompt: { de: 'Was ist 567 + 433?', en: 'What is 567 + 433?' },
    options: [{ value: '1000', label: { de: '1000', en: '1000' } }, { value: '990', label: { de: '990', en: '990' } }, { value: '900', label: { de: '900', en: '900' } }, { value: '1010', label: { de: '1010', en: '1010' } }],
    correctAnswer: '1000' },
  { id: 'mk3-033', type: 'true_false', subject: 'math', klasse: 3, difficulty: 1, topic: 'addition',
    prompt: { de: '250 + 150 = 400. Stimmt das?', en: '250 + 150 = 400. Is this correct?' },
    correctAnswer: true },

  // --- Subtraction ---
  { id: 'mk3-034', type: 'number_input', subject: 'math', klasse: 3, difficulty: 1, topic: 'subtraction',
    prompt: { de: 'Was ist 400 - 125?', en: 'What is 400 - 125?' },
    correctAnswer: 275 },
  { id: 'mk3-035', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'subtraction',
    prompt: { de: 'Was ist 703 - 456?', en: 'What is 703 - 456?' },
    options: [{ value: '247', label: { de: '247', en: '247' } }, { value: '257', label: { de: '257', en: '257' } }, { value: '347', label: { de: '347', en: '347' } }, { value: '237', label: { de: '237', en: '237' } }],
    correctAnswer: '247' },
  { id: 'mk3-036', type: 'number_input', subject: 'math', klasse: 3, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 1000 - 648?', en: 'What is 1000 - 648?' },
    correctAnswer: 352 },
  { id: 'mk3-037', type: 'true_false', subject: 'math', klasse: 3, difficulty: 2, topic: 'subtraction',
    prompt: { de: '600 - 275 = 325. Stimmt das?', en: '600 - 275 = 325. Is this correct?' },
    correctAnswer: true },
  { id: 'mk3-038', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 3, topic: 'subtraction',
    prompt: { de: 'Was ist 851 - 479?', en: 'What is 851 - 479?' },
    options: [{ value: '372', label: { de: '372', en: '372' } }, { value: '382', label: { de: '382', en: '382' } }, { value: '362', label: { de: '362', en: '362' } }, { value: '472', label: { de: '472', en: '472' } }],
    correctAnswer: '372' },

  // --- Geometry ---
  { id: 'mk3-039', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'geometry',
    prompt: { de: 'Wie viele Ecken hat ein Quadrat?', en: 'How many corners does a square have?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '6', label: { de: '6', en: '6' } }],
    correctAnswer: '4' },
  { id: 'mk3-040', type: 'true_false', subject: 'math', klasse: 3, difficulty: 1, topic: 'geometry',
    prompt: { de: 'Ein Rechteck hat 4 gleich lange Seiten. Stimmt das?', en: 'A rectangle has 4 sides of equal length. Is this correct?' },
    correctAnswer: false },
  { id: 'mk3-041', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'geometry',
    prompt: { de: 'Welche Form hat 5 Ecken?', en: 'Which shape has 5 corners?' },
    options: [{ value: 'Fünfeck', label: { de: 'Fünfeck', en: 'Pentagon' } }, { value: 'Sechseck', label: { de: 'Sechseck', en: 'Hexagon' } }, { value: 'Viereck', label: { de: 'Viereck', en: 'Quadrilateral' } }, { value: 'Achteck', label: { de: 'Achteck', en: 'Octagon' } }],
    correctAnswer: 'Fünfeck' },
  { id: 'mk3-042', type: 'true_false', subject: 'math', klasse: 3, difficulty: 2, topic: 'geometry',
    prompt: { de: 'Ein Kreis hat keine Ecken. Stimmt das?', en: 'A circle has no corners. Is this correct?' },
    correctAnswer: true },

  // --- Time ---
  { id: 'mk3-043', type: 'number_input', subject: 'math', klasse: 3, difficulty: 1, topic: 'time',
    prompt: { de: 'Wie viele Stunden hat ein Tag?', en: 'How many hours are in a day?' },
    correctAnswer: 24 },
  { id: 'mk3-044', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'time',
    prompt: { de: 'Wie viele Tage hat eine Woche?', en: 'How many days are in a week?' },
    options: [{ value: '7', label: { de: '7', en: '7' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '6', label: { de: '6', en: '6' } }, { value: '10', label: { de: '10', en: '10' } }],
    correctAnswer: '7' },
  { id: 'mk3-045', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'time',
    prompt: { de: 'Wie viele Monate hat ein Jahr?', en: 'How many months are in a year?' },
    options: [{ value: '12', label: { de: '12', en: '12' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '11', label: { de: '11', en: '11' } }, { value: '14', label: { de: '14', en: '14' } }],
    correctAnswer: '12' },

  // --- Measurement ---
  { id: 'mk3-046', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 1, topic: 'measurement',
    prompt: { de: 'Wie viele Zentimeter sind 1 Meter?', en: 'How many centimeters are in 1 meter?' },
    options: [{ value: '100', label: { de: '100', en: '100' } }, { value: '10', label: { de: '10', en: '10' } }, { value: '1000', label: { de: '1000', en: '1000' } }, { value: '50', label: { de: '50', en: '50' } }],
    correctAnswer: '100' },
  { id: 'mk3-047', type: 'number_input', subject: 'math', klasse: 3, difficulty: 2, topic: 'measurement',
    prompt: { de: 'Wie viele Gramm sind 1 Kilogramm?', en: 'How many grams are in 1 kilogram?' },
    correctAnswer: 1000 },
  { id: 'mk3-048', type: 'multiple_choice', subject: 'math', klasse: 3, difficulty: 2, topic: 'measurement',
    prompt: { de: 'Wie viele Milliliter sind 1 Liter?', en: 'How many milliliters are in 1 liter?' },
    options: [{ value: '1000', label: { de: '1000', en: '1000' } }, { value: '100', label: { de: '100', en: '100' } }, { value: '500', label: { de: '500', en: '500' } }, { value: '10000', label: { de: '10000', en: '10000' } }],
    correctAnswer: '1000' },
];
