import type { Question } from '../../../types/question';

export const deutschKlasse1: Question[] = [
  // --- Original 12 questions (dk1-001 through dk1-012) ---
  { id: 'dk1-001', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe kommt nach A?', en: 'Which letter comes after A?' },
    options: [{ value: 'B', label: { de: 'B', en: 'B' } }, { value: 'C', label: { de: 'C', en: 'C' } }, { value: 'D', label: { de: 'D', en: 'D' } }, { value: 'A', label: { de: 'A', en: 'A' } }],
    correctAnswer: 'B' },
  { id: 'dk1-002', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Mit welchem Buchstaben fängt "Hund" an?', en: 'What letter does "Hund" (dog) start with?' },
    options: [{ value: 'H', label: { de: 'H', en: 'H' } }, { value: 'D', label: { de: 'D', en: 'D' } }, { value: 'B', label: { de: 'B', en: 'B' } }, { value: 'K', label: { de: 'K', en: 'K' } }],
    correctAnswer: 'H' },
  { id: 'dk1-003', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Mit welchem Buchstaben fängt "Katze" an?', en: 'What letter does "Katze" (cat) start with?' },
    options: [{ value: 'K', label: { de: 'K', en: 'K' } }, { value: 'C', label: { de: 'C', en: 'C' } }, { value: 'G', label: { de: 'G', en: 'G' } }, { value: 'T', label: { de: 'T', en: 'T' } }],
    correctAnswer: 'K' },
  { id: 'dk1-004', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Mama"?', en: 'How many syllables does "Mama" have?' },
    options: [{ value: '2', label: { de: '2', en: '2' } }, { value: '1', label: { de: '1', en: '1' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '4', label: { de: '4', en: '4' } }],
    correctAnswer: '2' },
  { id: 'dk1-005', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Schmetterling"?', en: 'How many syllables does "Schmetterling" (butterfly) have?' },
    options: [{ value: '3', label: { de: '3', en: '3' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '1', label: { de: '1', en: '1' } }],
    correctAnswer: '3' },
  { id: 'dk1-006', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Ein Tier das bellt', en: 'Build the word: An animal that barks' },
    letters: ['H', 'U', 'N', 'D'],
    correctWord: 'HUND',
    hint: { de: 'Es fängt mit H an', en: 'It starts with H' } },
  { id: 'dk1-007', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Sie scheint am Himmel', en: 'Build the word: It shines in the sky' },
    letters: ['S', 'O', 'N', 'N', 'E'],
    correctWord: 'SONNE',
    hint: { de: 'Es fängt mit S an', en: 'It starts with S' } },
  { id: 'dk1-008', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Man sitzt darauf', en: 'Build the word: You sit on it' },
    letters: ['S', 'T', 'U', 'H', 'L'],
    correctWord: 'STUHL',
    hint: { de: 'Es fängt mit St an', en: 'It starts with St' } },
  { id: 'dk1-009', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe fehlt? _pfel', en: 'Which letter is missing? _pfel (apple)' },
    options: [{ value: 'A', label: { de: 'A', en: 'A' } }, { value: 'E', label: { de: 'E', en: 'E' } }, { value: 'O', label: { de: 'O', en: 'O' } }, { value: 'U', label: { de: 'U', en: 'U' } }],
    correctAnswer: 'A' },
  { id: 'dk1-010', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe fehlt? Bl_me', en: 'Which letter is missing? Bl_me (flower)' },
    options: [{ value: 'u', label: { de: 'u', en: 'u' } }, { value: 'a', label: { de: 'a', en: 'a' } }, { value: 'i', label: { de: 'i', en: 'i' } }, { value: 'e', label: { de: 'e', en: 'e' } }],
    correctAnswer: 'u' },
  { id: 'dk1-011', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Ein rotes Obst', en: 'Build the word: A red fruit' },
    letters: ['A', 'P', 'F', 'E', 'L'],
    correctWord: 'APFEL' },
  { id: 'dk1-012', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Ball"?', en: 'How many syllables does "Ball" have?' },
    options: [{ value: '1', label: { de: '1', en: '1' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '3', label: { de: '3', en: '3' } }],
    correctAnswer: '1' },

  // --- New questions (dk1-013 through dk1-048) ---

  // Letters - multiple_choice
  { id: 'dk1-013', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe kommt nach D?', en: 'Which letter comes after D?' },
    options: [{ value: 'E', label: { de: 'E', en: 'E' } }, { value: 'F', label: { de: 'F', en: 'F' } }, { value: 'C', label: { de: 'C', en: 'C' } }, { value: 'G', label: { de: 'G', en: 'G' } }],
    correctAnswer: 'E' },
  { id: 'dk1-014', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Mit welchem Buchstaben fängt "Baum" an?', en: 'What letter does "Baum" (tree) start with?' },
    options: [{ value: 'B', label: { de: 'B', en: 'B' } }, { value: 'D', label: { de: 'D', en: 'D' } }, { value: 'P', label: { de: 'P', en: 'P' } }, { value: 'M', label: { de: 'M', en: 'M' } }],
    correctAnswer: 'B' },
  { id: 'dk1-015', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Mit welchem Buchstaben fängt "Maus" an?', en: 'What letter does "Maus" (mouse) start with?' },
    options: [{ value: 'M', label: { de: 'M', en: 'M' } }, { value: 'N', label: { de: 'N', en: 'N' } }, { value: 'L', label: { de: 'L', en: 'L' } }, { value: 'R', label: { de: 'R', en: 'R' } }],
    correctAnswer: 'M' },
  { id: 'dk1-016', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'letters',
    prompt: { de: 'Mit welchem Buchstaben endet "Maus"?', en: 'What letter does "Maus" (mouse) end with?' },
    options: [{ value: 'S', label: { de: 'S', en: 'S' } }, { value: 'M', label: { de: 'M', en: 'M' } }, { value: 'U', label: { de: 'U', en: 'U' } }, { value: 'Z', label: { de: 'Z', en: 'Z' } }],
    correctAnswer: 'S' },
  { id: 'dk1-017', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe kommt nach M?', en: 'Which letter comes after M?' },
    options: [{ value: 'N', label: { de: 'N', en: 'N' } }, { value: 'O', label: { de: 'O', en: 'O' } }, { value: 'L', label: { de: 'L', en: 'L' } }, { value: 'P', label: { de: 'P', en: 'P' } }],
    correctAnswer: 'N' },
  { id: 'dk1-018', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe fehlt? H_us', en: 'Which letter is missing? H_us (house)' },
    options: [{ value: 'a', label: { de: 'a', en: 'a' } }, { value: 'e', label: { de: 'e', en: 'e' } }, { value: 'o', label: { de: 'o', en: 'o' } }, { value: 'u', label: { de: 'u', en: 'u' } }],
    correctAnswer: 'a' },
  { id: 'dk1-019', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'letters',
    prompt: { de: 'Welcher Buchstabe fehlt? F_sch', en: 'Which letter is missing? F_sch (fish)' },
    options: [{ value: 'i', label: { de: 'i', en: 'i' } }, { value: 'a', label: { de: 'a', en: 'a' } }, { value: 'u', label: { de: 'u', en: 'u' } }, { value: 'o', label: { de: 'o', en: 'o' } }],
    correctAnswer: 'i' },
  { id: 'dk1-020', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'letters',
    prompt: { de: 'Mit welchem Buchstaben endet "Ball"?', en: 'What letter does "Ball" end with?' },
    options: [{ value: 'L', label: { de: 'L', en: 'L' } }, { value: 'B', label: { de: 'B', en: 'B' } }, { value: 'A', label: { de: 'A', en: 'A' } }, { value: 'N', label: { de: 'N', en: 'N' } }],
    correctAnswer: 'L' },

  // Syllables - multiple_choice
  { id: 'dk1-021', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Banane"?', en: 'How many syllables does "Banane" (banana) have?' },
    options: [{ value: '3', label: { de: '3', en: '3' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '1', label: { de: '1', en: '1' } }],
    correctAnswer: '3' },
  { id: 'dk1-022', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Auto"?', en: 'How many syllables does "Auto" (car) have?' },
    options: [{ value: '2', label: { de: '2', en: '2' } }, { value: '1', label: { de: '1', en: '1' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '4', label: { de: '4', en: '4' } }],
    correctAnswer: '2' },
  { id: 'dk1-023', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Tisch"?', en: 'How many syllables does "Tisch" (table) have?' },
    options: [{ value: '1', label: { de: '1', en: '1' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '4', label: { de: '4', en: '4' } }],
    correctAnswer: '1' },
  { id: 'dk1-024', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Tomate"?', en: 'How many syllables does "Tomate" (tomato) have?' },
    options: [{ value: '3', label: { de: '3', en: '3' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '1', label: { de: '1', en: '1' } }],
    correctAnswer: '3' },
  { id: 'dk1-025', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Schokolade"?', en: 'How many syllables does "Schokolade" (chocolate) have?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '2', label: { de: '2', en: '2' } }],
    correctAnswer: '4' },
  { id: 'dk1-026', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Kindergarten"?', en: 'How many syllables does "Kindergarten" have?' },
    options: [{ value: '4', label: { de: '4', en: '4' } }, { value: '3', label: { de: '3', en: '3' } }, { value: '5', label: { de: '5', en: '5' } }, { value: '2', label: { de: '2', en: '2' } }],
    correctAnswer: '4' },
  { id: 'dk1-027', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: 'Wie viele Silben hat "Elefant"?', en: 'How many syllables does "Elefant" (elephant) have?' },
    options: [{ value: '3', label: { de: '3', en: '3' } }, { value: '2', label: { de: '2', en: '2' } }, { value: '4', label: { de: '4', en: '4' } }, { value: '1', label: { de: '1', en: '1' } }],
    correctAnswer: '3' },

  // Spelling - word_build
  { id: 'dk1-028', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Man spielt damit', en: 'Build the word: You play with it' },
    letters: ['B', 'A', 'L', 'L'],
    correctWord: 'BALL',
    hint: { de: 'Es fängt mit B an', en: 'It starts with B' } },
  { id: 'dk1-029', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Er wächst im Wald', en: 'Build the word: It grows in the forest' },
    letters: ['B', 'A', 'U', 'M'],
    correctWord: 'BAUM',
    hint: { de: 'Es fängt mit B an', en: 'It starts with B' } },
  { id: 'dk1-030', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Ein kleines Tier mit langem Schwanz', en: 'Build the word: A small animal with a long tail' },
    letters: ['M', 'A', 'U', 'S'],
    correctWord: 'MAUS',
    hint: { de: 'Es fängt mit M an', en: 'It starts with M' } },
  { id: 'dk1-031', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Man wohnt darin', en: 'Build the word: You live in it' },
    letters: ['H', 'A', 'U', 'S'],
    correctWord: 'HAUS',
    hint: { de: 'Es fängt mit H an', en: 'It starts with H' } },
  { id: 'dk1-032', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Er schwimmt im Wasser', en: 'Build the word: It swims in the water' },
    letters: ['F', 'I', 'S', 'C', 'H'],
    correctWord: 'FISCH',
    hint: { de: 'Es fängt mit F an', en: 'It starts with F' } },
  { id: 'dk1-033', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Er kann fliegen und hat Federn', en: 'Build the word: It can fly and has feathers' },
    letters: ['V', 'O', 'G', 'E', 'L'],
    correctWord: 'VOGEL',
    hint: { de: 'Es fängt mit V an', en: 'It starts with V' } },
  { id: 'dk1-034', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Er leuchtet am Nachthimmel', en: 'Build the word: It shines in the night sky' },
    letters: ['S', 'T', 'E', 'R', 'N'],
    correctWord: 'STERN',
    hint: { de: 'Es fängt mit St an', en: 'It starts with St' } },
  { id: 'dk1-035', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Sie wächst im Garten und ist bunt', en: 'Build the word: It grows in the garden and is colorful' },
    letters: ['B', 'L', 'U', 'M', 'E'],
    correctWord: 'BLUME',
    hint: { de: 'Es fängt mit Bl an', en: 'It starts with Bl' } },
  { id: 'dk1-036', type: 'word_build', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Eine große gestreifte Katze', en: 'Build the word: A big striped cat' },
    letters: ['T', 'I', 'G', 'E', 'R'],
    correctWord: 'TIGER',
    hint: { de: 'Es fängt mit T an', en: 'It starts with T' } },

  // Vowels - multiple_choice
  { id: 'dk1-037', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'vowels',
    prompt: { de: 'Welcher dieser Buchstaben ist ein Selbstlaut (Vokal)?', en: 'Which of these letters is a vowel?' },
    options: [{ value: 'A', label: { de: 'A', en: 'A' } }, { value: 'B', label: { de: 'B', en: 'B' } }, { value: 'K', label: { de: 'K', en: 'K' } }, { value: 'T', label: { de: 'T', en: 'T' } }],
    correctAnswer: 'A' },
  { id: 'dk1-038', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'vowels',
    prompt: { de: 'Welcher dieser Buchstaben ist ein Selbstlaut (Vokal)?', en: 'Which of these letters is a vowel?' },
    options: [{ value: 'E', label: { de: 'E', en: 'E' } }, { value: 'R', label: { de: 'R', en: 'R' } }, { value: 'S', label: { de: 'S', en: 'S' } }, { value: 'N', label: { de: 'N', en: 'N' } }],
    correctAnswer: 'E' },
  { id: 'dk1-039', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'vowels',
    prompt: { de: 'Welcher Selbstlaut (Vokal) steckt in dem Wort "Hut"?', en: 'Which vowel is in the word "Hut" (hat)?' },
    options: [{ value: 'U', label: { de: 'U', en: 'U' } }, { value: 'A', label: { de: 'A', en: 'A' } }, { value: 'I', label: { de: 'I', en: 'I' } }, { value: 'O', label: { de: 'O', en: 'O' } }],
    correctAnswer: 'U' },
  { id: 'dk1-040', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'vowels',
    prompt: { de: 'Welcher Selbstlaut (Vokal) steckt in dem Wort "Topf"?', en: 'Which vowel is in the word "Topf" (pot)?' },
    options: [{ value: 'O', label: { de: 'O', en: 'O' } }, { value: 'A', label: { de: 'A', en: 'A' } }, { value: 'U', label: { de: 'U', en: 'U' } }, { value: 'E', label: { de: 'E', en: 'E' } }],
    correctAnswer: 'O' },

  // Rhyming - multiple_choice
  { id: 'dk1-041', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'rhyming',
    prompt: { de: 'Welches Wort reimt sich auf "Haus"?', en: 'Which word rhymes with "Haus" (house)?' },
    options: [{ value: 'Maus', label: { de: 'Maus', en: 'Maus (mouse)' } }, { value: 'Hund', label: { de: 'Hund', en: 'Hund (dog)' } }, { value: 'Baum', label: { de: 'Baum', en: 'Baum (tree)' } }, { value: 'Tisch', label: { de: 'Tisch', en: 'Tisch (table)' } }],
    correctAnswer: 'Maus' },
  { id: 'dk1-042', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'rhyming',
    prompt: { de: 'Welches Wort reimt sich auf "Katze"?', en: 'Which word rhymes with "Katze" (cat)?' },
    options: [{ value: 'Tatze', label: { de: 'Tatze', en: 'Tatze (paw)' } }, { value: 'Blume', label: { de: 'Blume', en: 'Blume (flower)' } }, { value: 'Sonne', label: { de: 'Sonne', en: 'Sonne (sun)' } }, { value: 'Vogel', label: { de: 'Vogel', en: 'Vogel (bird)' } }],
    correctAnswer: 'Tatze' },
  { id: 'dk1-043', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'rhyming',
    prompt: { de: 'Welches Wort reimt sich auf "Hund"?', en: 'Which word rhymes with "Hund" (dog)?' },
    options: [{ value: 'Mund', label: { de: 'Mund', en: 'Mund (mouth)' } }, { value: 'Katze', label: { de: 'Katze', en: 'Katze (cat)' } }, { value: 'Fisch', label: { de: 'Fisch', en: 'Fisch (fish)' } }, { value: 'Stern', label: { de: 'Stern', en: 'Stern (star)' } }],
    correctAnswer: 'Mund' },
  { id: 'dk1-044', type: 'multiple_choice', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'rhyming',
    prompt: { de: 'Welches Wort reimt sich auf "Nacht"?', en: 'Which word rhymes with "Nacht" (night)?' },
    options: [{ value: 'acht', label: { de: 'acht', en: 'acht (eight)' } }, { value: 'Stern', label: { de: 'Stern', en: 'Stern (star)' } }, { value: 'Mond', label: { de: 'Mond', en: 'Mond (moon)' } }, { value: 'Tag', label: { de: 'Tag', en: 'Tag (day)' } }],
    correctAnswer: 'acht' },

  // True/False
  { id: 'dk1-045', type: 'true_false', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: '"Hund" fängt mit dem Buchstaben H an.', en: '"Hund" (dog) starts with the letter H.' },
    correctAnswer: true },
  { id: 'dk1-046', type: 'true_false', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'syllables',
    prompt: { de: '"Ball" hat 3 Silben.', en: '"Ball" has 3 syllables.' },
    correctAnswer: false },
  { id: 'dk1-047', type: 'true_false', subject: 'deutsch', klasse: 1, difficulty: 1, topic: 'letters',
    prompt: { de: '"Sonne" fängt mit dem Buchstaben S an.', en: '"Sonne" (sun) starts with the letter S.' },
    correctAnswer: true },
  { id: 'dk1-048', type: 'true_false', subject: 'deutsch', klasse: 1, difficulty: 2, topic: 'vowels',
    prompt: { de: 'Der Buchstabe "B" ist ein Selbstlaut (Vokal).', en: 'The letter "B" is a vowel.' },
    correctAnswer: false },
];
