import type { Question } from '../../../types/question';

export const deutschKlasse4: Question[] = [
  { id: 'dk4-001', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Welches Wort ist ein Verb (Tunwort)?', en: 'Which word is a verb?' },
    options: [{ value: 'laufen', label: { de: 'laufen', en: 'laufen (to run)' } }, { value: 'Tisch', label: { de: 'Tisch', en: 'Tisch (table)' } }, { value: 'schön', label: { de: 'schön', en: 'schön (beautiful)' } }, { value: 'schnell', label: { de: 'schnell', en: 'schnell (fast)' } }],
    correctAnswer: 'laufen' },
  { id: 'dk4-002', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Feuer" + "wehr"?', en: 'What does "Feuer" + "wehr" make?' },
    options: [{ value: 'Feuerwehr', label: { de: 'Feuerwehr', en: 'Feuerwehr (fire department)' } }, { value: 'FeuerWehr', label: { de: 'FeuerWehr', en: 'FeuerWehr' } }, { value: 'Feuwehr', label: { de: 'Feuwehr', en: 'Feuwehr' } }],
    correctAnswer: 'Feuerwehr' },
  { id: 'dk4-003', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort wird mit "ä" geschrieben?', en: 'Which word is written with "ä"?' },
    options: [{ value: 'Bäcker', label: { de: 'Bäcker', en: 'Bäcker (baker)' } }, { value: 'Becker', label: { de: 'Becker', en: 'Becker' } }, { value: 'Backer', label: { de: 'Backer', en: 'Backer' } }],
    correctAnswer: 'Bäcker' },
  { id: 'dk4-004', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 2, topic: 'verbs',
    prompt: { de: 'Was ist die Vergangenheitsform von "gehen"?', en: 'What is the past tense of "gehen" (to go)?' },
    options: [{ value: 'ging', label: { de: 'ging', en: 'ging' } }, { value: 'geht', label: { de: 'geht', en: 'geht' } }, { value: 'ginge', label: { de: 'ginge', en: 'ginge' } }, { value: 'gehte', label: { de: 'gehte', en: 'gehte' } }],
    correctAnswer: 'ging' },
  { id: 'dk4-005', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 3, topic: 'sentences',
    prompt: { de: 'Welcher Satz hat die richtige Wortstellung?', en: 'Which sentence has the correct word order?' },
    options: [
      { value: 'correct', label: { de: 'Gestern bin ich ins Kino gegangen.', en: 'Gestern bin ich ins Kino gegangen.' } },
      { value: 'wrong1', label: { de: 'Gestern ich bin ins Kino gegangen.', en: 'Gestern ich bin ins Kino gegangen.' } },
      { value: 'wrong2', label: { de: 'Ich gestern bin ins Kino gegangen.', en: 'Ich gestern bin ins Kino gegangen.' } },
    ],
    correctAnswer: 'correct',
    explanation: { de: 'Nach einer Zeitangabe am Satzanfang kommt das Verb an zweiter Stelle!', en: 'After a time expression at the beginning, the verb comes in second position!' } },
  { id: 'dk4-006', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Steigere das Adjektiv: schnell, schneller, ___', en: 'Compare the adjective: schnell, schneller, ___' },
    options: [{ value: 'am schnellsten', label: { de: 'am schnellsten', en: 'am schnellsten' } }, { value: 'schnellster', label: { de: 'schnellster', en: 'schnellster' } }, { value: 'schnellest', label: { de: 'schnellest', en: 'schnellest' } }],
    correctAnswer: 'am schnellsten' },
  { id: 'dk4-007', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig? Ich ___ Fußball.', en: 'Which is correct? Ich ___ Fußball (I play soccer).' },
    options: [{ value: 'spiele', label: { de: 'spiele', en: 'spiele' } }, { value: 'schpiele', label: { de: 'schpiele', en: 'schpiele' } }, { value: 'spihle', label: { de: 'spihle', en: 'spihle' } }],
    correctAnswer: 'spiele' },
  { id: 'dk4-008', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 3, topic: 'nouns',
    prompt: { de: 'Was ist die Mehrzahl von "Maus"?', en: 'What is the plural of "Maus" (mouse)?' },
    options: [{ value: 'Mäuse', label: { de: 'Mäuse', en: 'Mäuse' } }, { value: 'Mause', label: { de: 'Mause', en: 'Mause' } }, { value: 'Mäusen', label: { de: 'Mäusen', en: 'Mäusen' } }, { value: 'Mauser', label: { de: 'Mauser', en: 'Mauser' } }],
    correctAnswer: 'Mäuse' },
  { id: 'dk4-009', type: 'multiple_choice', subject: 'deutsch', klasse: 4, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Mädchen', en: 'Which article fits? ___ Mädchen (girl)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }],
    correctAnswer: 'das',
    explanation: { de: 'Mädchen ist sächlich wegen der Endung "-chen"!', en: '"Mädchen" is neuter because of the "-chen" ending!' } },
  { id: 'dk4-010', type: 'word_build', subject: 'deutsch', klasse: 4, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Baue das Wort: Geburtstag + Kuchen', en: 'Build the word: Birthday + cake' },
    letters: ['G', 'E', 'B', 'U', 'R', 'T', 'S', 'T', 'A', 'G', 'S', 'K', 'U', 'C', 'H', 'E', 'N'],
    correctWord: 'GEBURTSTAGSKUCHEN' },
];
