import type { Question } from '../../../types/question';

export const deutschKlasse3: Question[] = [
  // === ORIGINAL 10 QUESTIONS (dk3-001 to dk3-010) ===
  { id: 'dk3-001', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "groß"?', en: 'What is the opposite of "groß" (big)?' },
    options: [{ value: 'klein', label: { de: 'klein', en: 'klein (small)' } }, { value: 'lang', label: { de: 'lang', en: 'lang (long)' } }, { value: 'dick', label: { de: 'dick', en: 'dick (thick)' } }, { value: 'alt', label: { de: 'alt', en: 'alt (old)' } }],
    correctAnswer: 'klein' },
  { id: 'dk3-002', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "heiß"?', en: 'What is the opposite of "heiß" (hot)?' },
    options: [{ value: 'kalt', label: { de: 'kalt', en: 'kalt (cold)' } }, { value: 'warm', label: { de: 'warm', en: 'warm (warm)' } }, { value: 'nass', label: { de: 'nass', en: 'nass (wet)' } }, { value: 'trocken', label: { de: 'trocken', en: 'trocken (dry)' } }],
    correctAnswer: 'kalt' },
  { id: 'dk3-003', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Welches zusammengesetzte Wort ist richtig?', en: 'Which compound word is correct?' },
    options: [{ value: 'Haustür', label: { de: 'Haustür', en: 'Haustür (front door)' } }, { value: 'HausTür', label: { de: 'HausTür', en: 'HausTür' } }, { value: 'Haus Tür', label: { de: 'Haus Tür', en: 'Haus Tür' } }, { value: 'haustur', label: { de: 'haustur', en: 'haustur' } }],
    correctAnswer: 'Haustür' },
  { id: 'dk3-004', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Schul" + "tasche"?', en: 'What does "Schul" + "tasche" make?' },
    options: [{ value: 'Schultasche', label: { de: 'Schultasche', en: 'Schultasche (school bag)' } }, { value: 'SchulTasche', label: { de: 'SchulTasche', en: 'SchulTasche' } }, { value: 'Schulltasche', label: { de: 'Schulltasche', en: 'Schulltasche' } }],
    correctAnswer: 'Schultasche' },
  { id: 'dk3-005', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Ich ___ schnell.', en: 'Which form is correct? Ich ___ schnell. (I ___ fast.)' },
    options: [{ value: 'laufe', label: { de: 'laufe', en: 'laufe' } }, { value: 'laufst', label: { de: 'laufst', en: 'laufst' } }, { value: 'lauft', label: { de: 'lauft', en: 'lauft' } }, { value: 'laufen', label: { de: 'laufen', en: 'laufen' } }],
    correctAnswer: 'laufe' },
  { id: 'dk3-006', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Er ___ ein Buch.', en: 'Which form is correct? Er ___ ein Buch. (He ___ a book.)' },
    options: [{ value: 'liest', label: { de: 'liest', en: 'liest' } }, { value: 'lest', label: { de: 'lest', en: 'lest' } }, { value: 'lese', label: { de: 'lese', en: 'lese' } }, { value: 'lesen', label: { de: 'lesen', en: 'lesen' } }],
    correctAnswer: 'liest' },
  { id: 'dk3-007', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "leise"?', en: 'What is the opposite of "leise" (quiet)?' },
    options: [{ value: 'laut', label: { de: 'laut', en: 'laut (loud)' } }, { value: 'schnell', label: { de: 'schnell', en: 'schnell (fast)' } }, { value: 'dunkel', label: { de: 'dunkel', en: 'dunkel (dark)' } }, { value: 'hell', label: { de: 'hell', en: 'hell (bright)' } }],
    correctAnswer: 'laut' },
  { id: 'dk3-008', type: 'word_build', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Baue das Wort: Tasche für die Schule', en: 'Build the word: bag for school' },
    letters: ['S', 'C', 'H', 'U', 'L', 'T', 'A', 'S', 'C', 'H', 'E'],
    correctWord: 'SCHULTASCHE' },
  { id: 'dk3-009', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'verbs',
    prompt: { de: 'Welche Zeitform ist "Ich habe gespielt"?', en: 'What tense is "Ich habe gespielt" (I have played)?' },
    options: [{ value: 'perfekt', label: { de: 'Perfekt (Vergangenheit)', en: 'Perfect (past)' } }, { value: 'präsens', label: { de: 'Präsens (Gegenwart)', en: 'Present' } }, { value: 'futur', label: { de: 'Futur (Zukunft)', en: 'Future' } }],
    correctAnswer: 'perfekt' },
  { id: 'dk3-010', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Was ist die Mehrzahl von "Kind"?', en: 'What is the plural of "Kind" (child)?' },
    options: [{ value: 'Kinder', label: { de: 'Kinder', en: 'Kinder' } }, { value: 'Kinds', label: { de: 'Kinds', en: 'Kinds' } }, { value: 'Kindern', label: { de: 'Kindern', en: 'Kindern' } }, { value: 'Kindere', label: { de: 'Kindere', en: 'Kindere' } }],
    correctAnswer: 'Kinder' },

  // === NEW QUESTIONS (dk3-011 to dk3-040) ===

  // --- Adjectives: Opposites ---
  { id: 'dk3-011', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "hell"?', en: 'What is the opposite of "hell" (bright)?' },
    options: [{ value: 'dunkel', label: { de: 'dunkel', en: 'dunkel (dark)' } }, { value: 'laut', label: { de: 'laut', en: 'laut (loud)' } }, { value: 'schwer', label: { de: 'schwer', en: 'schwer (heavy)' } }, { value: 'weich', label: { de: 'weich', en: 'weich (soft)' } }],
    correctAnswer: 'dunkel' },
  { id: 'dk3-012', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "alt"?', en: 'What is the opposite of "alt" (old)?' },
    options: [{ value: 'jung', label: { de: 'jung', en: 'jung (young)' } }, { value: 'neu', label: { de: 'neu', en: 'neu (new)' } }, { value: 'klein', label: { de: 'klein', en: 'klein (small)' } }, { value: 'kurz', label: { de: 'kurz', en: 'kurz (short)' } }],
    correctAnswer: 'jung' },
  { id: 'dk3-013', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "schnell"?', en: 'What is the opposite of "schnell" (fast)?' },
    options: [{ value: 'langsam', label: { de: 'langsam', en: 'langsam (slow)' } }, { value: 'leise', label: { de: 'leise', en: 'leise (quiet)' } }, { value: 'schwer', label: { de: 'schwer', en: 'schwer (heavy)' } }, { value: 'dunkel', label: { de: 'dunkel', en: 'dunkel (dark)' } }],
    correctAnswer: 'langsam' },
  { id: 'dk3-014', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "schwer"?', en: 'What is the opposite of "schwer" (heavy)?' },
    options: [{ value: 'leicht', label: { de: 'leicht', en: 'leicht (light)' } }, { value: 'klein', label: { de: 'klein', en: 'klein (small)' } }, { value: 'dünn', label: { de: 'dünn', en: 'dünn (thin)' } }, { value: 'kurz', label: { de: 'kurz', en: 'kurz (short)' } }],
    correctAnswer: 'leicht' },
  { id: 'dk3-015', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "nass"?', en: 'What is the opposite of "nass" (wet)?' },
    options: [{ value: 'trocken', label: { de: 'trocken', en: 'trocken (dry)' } }, { value: 'kalt', label: { de: 'kalt', en: 'kalt (cold)' } }, { value: 'hart', label: { de: 'hart', en: 'hart (hard)' } }, { value: 'warm', label: { de: 'warm', en: 'warm (warm)' } }],
    correctAnswer: 'trocken' },
  { id: 'dk3-016', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "dick"?', en: 'What is the opposite of "dick" (thick/fat)?' },
    options: [{ value: 'dünn', label: { de: 'dünn', en: 'dünn (thin)' } }, { value: 'klein', label: { de: 'klein', en: 'klein (small)' } }, { value: 'leicht', label: { de: 'leicht', en: 'leicht (light)' } }, { value: 'kurz', label: { de: 'kurz', en: 'kurz (short)' } }],
    correctAnswer: 'dünn' },
  { id: 'dk3-017', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'adjectives',
    prompt: { de: 'Welche Steigerung ist richtig? gut, ___', en: 'Which comparative form is correct? gut (good), ___' },
    options: [{ value: 'besser', label: { de: 'besser', en: 'besser (better)' } }, { value: 'guter', label: { de: 'guter', en: 'guter' } }, { value: 'güter', label: { de: 'güter', en: 'güter' } }, { value: 'mehr gut', label: { de: 'mehr gut', en: 'mehr gut' } }],
    correctAnswer: 'besser' },
  { id: 'dk3-018', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'adjectives',
    prompt: { de: 'Welche Steigerung ist richtig? viel, ___', en: 'Which comparative form is correct? viel (much), ___' },
    options: [{ value: 'mehr', label: { de: 'mehr', en: 'mehr (more)' } }, { value: 'vieler', label: { de: 'vieler', en: 'vieler' } }, { value: 'vielest', label: { de: 'vielest', en: 'vielest' } }, { value: 'am vielsten', label: { de: 'am vielsten', en: 'am vielsten' } }],
    correctAnswer: 'mehr' },

  // --- Compound words ---
  { id: 'dk3-019', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Schnee" + "Mann"?', en: 'What does "Schnee" (snow) + "Mann" (man) make?' },
    options: [{ value: 'Schneemann', label: { de: 'Schneemann', en: 'Schneemann (snowman)' } }, { value: 'SchneeMannn', label: { de: 'SchneeMannn', en: 'SchneeMannn' } }, { value: 'Schnee Mann', label: { de: 'Schnee Mann', en: 'Schnee Mann' } }, { value: 'schneemann', label: { de: 'schneemann', en: 'schneemann' } }],
    correctAnswer: 'Schneemann' },
  { id: 'dk3-020', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Fuß" + "Ball"?', en: 'What does "Fuß" (foot) + "Ball" (ball) make?' },
    options: [{ value: 'Fußball', label: { de: 'Fußball', en: 'Fußball (football/soccer)' } }, { value: 'FußBall', label: { de: 'FußBall', en: 'FußBall' } }, { value: 'Fuß Ball', label: { de: 'Fuß Ball', en: 'Fuß Ball' } }, { value: 'Fussball', label: { de: 'Fussball', en: 'Fussball' } }],
    correctAnswer: 'Fußball' },
  { id: 'dk3-021', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Hand" + "Schuh"?', en: 'What does "Hand" (hand) + "Schuh" (shoe) make?' },
    options: [{ value: 'Handschuh', label: { de: 'Handschuh', en: 'Handschuh (glove)' } }, { value: 'HandSchuh', label: { de: 'HandSchuh', en: 'HandSchuh' } }, { value: 'Hand Schuh', label: { de: 'Hand Schuh', en: 'Hand Schuh' } }, { value: 'Handshuh', label: { de: 'Handshuh', en: 'Handshuh' } }],
    correctAnswer: 'Handschuh' },
  { id: 'dk3-022', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Regen" + "Schirm"?', en: 'What does "Regen" (rain) + "Schirm" (screen/shield) make?' },
    options: [{ value: 'Regenschirm', label: { de: 'Regenschirm', en: 'Regenschirm (umbrella)' } }, { value: 'RegenSchirm', label: { de: 'RegenSchirm', en: 'RegenSchirm' } }, { value: 'Regen Schirm', label: { de: 'Regen Schirm', en: 'Regen Schirm' } }, { value: 'Regensschirm', label: { de: 'Regensschirm', en: 'Regensschirm' } }],
    correctAnswer: 'Regenschirm' },
  { id: 'dk3-023', type: 'word_build', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Baue das Wort: Mann aus Schnee', en: 'Build the word: man made of snow' },
    letters: ['S', 'C', 'H', 'N', 'E', 'E', 'M', 'A', 'N', 'N'],
    correctWord: 'SCHNEEMANN' },
  { id: 'dk3-024', type: 'word_build', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'compound_words',
    prompt: { de: 'Baue das Wort: Topf für Blumen', en: 'Build the word: pot for flowers' },
    letters: ['B', 'L', 'U', 'M', 'E', 'N', 'T', 'O', 'P', 'F'],
    correctWord: 'BLUMENTOPF' },
  { id: 'dk3-025', type: 'word_build', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'compound_words',
    prompt: { de: 'Baue das Wort: Garten für Kinder', en: 'Build the word: garden for children' },
    letters: ['K', 'I', 'N', 'D', 'E', 'R', 'G', 'A', 'R', 'T', 'E', 'N'],
    correctWord: 'KINDERGARTEN' },

  // --- Verbs: conjugation and tenses ---
  { id: 'dk3-026', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Du ___ sehr gut.', en: 'Which form is correct? Du ___ sehr gut. (You ___ very well.)' },
    options: [{ value: 'singst', label: { de: 'singst', en: 'singst' } }, { value: 'singt', label: { de: 'singt', en: 'singt' } }, { value: 'singe', label: { de: 'singe', en: 'singe' } }, { value: 'singen', label: { de: 'singen', en: 'singen' } }],
    correctAnswer: 'singst' },
  { id: 'dk3-027', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Wir ___ nach Hause.', en: 'Which form is correct? Wir ___ nach Hause. (We ___ home.)' },
    options: [{ value: 'gehen', label: { de: 'gehen', en: 'gehen' } }, { value: 'geht', label: { de: 'geht', en: 'geht' } }, { value: 'gehst', label: { de: 'gehst', en: 'gehst' } }, { value: 'gehe', label: { de: 'gehe', en: 'gehe' } }],
    correctAnswer: 'gehen' },
  { id: 'dk3-028', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Er ___ einen Apfel.', en: 'Which form is correct? Er ___ einen Apfel. (He ___ an apple.)' },
    options: [{ value: 'isst', label: { de: 'isst', en: 'isst' } }, { value: 'esst', label: { de: 'esst', en: 'esst' } }, { value: 'esse', label: { de: 'esse', en: 'esse' } }, { value: 'essen', label: { de: 'essen', en: 'essen' } }],
    correctAnswer: 'isst' },
  { id: 'dk3-029', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Sie ___ mit dem Bus.', en: 'Which form is correct? Sie ___ mit dem Bus. (She ___ by bus.)' },
    options: [{ value: 'fährt', label: { de: 'fährt', en: 'fährt' } }, { value: 'fahrt', label: { de: 'fahrt', en: 'fahrt' } }, { value: 'fahre', label: { de: 'fahre', en: 'fahre' } }, { value: 'fahren', label: { de: 'fahren', en: 'fahren' } }],
    correctAnswer: 'fährt' },
  { id: 'dk3-030', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'verbs',
    prompt: { de: 'Wie lautet die Vergangenheit (Präteritum) von "gehen"?', en: 'What is the past tense (Präteritum) of "gehen" (to go)?' },
    options: [{ value: 'ging', label: { de: 'ging', en: 'ging (went)' } }, { value: 'geht', label: { de: 'geht', en: 'geht' } }, { value: 'gehte', label: { de: 'gehte', en: 'gehte' } }, { value: 'gegangen', label: { de: 'gegangen', en: 'gegangen' } }],
    correctAnswer: 'ging' },
  { id: 'dk3-031', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'verbs',
    prompt: { de: 'Wie lautet die Vergangenheit (Präteritum) von "kommen"?', en: 'What is the past tense (Präteritum) of "kommen" (to come)?' },
    options: [{ value: 'kam', label: { de: 'kam', en: 'kam (came)' } }, { value: 'kommte', label: { de: 'kommte', en: 'kommte' } }, { value: 'kommt', label: { de: 'kommt', en: 'kommt' } }, { value: 'gekommen', label: { de: 'gekommen', en: 'gekommen' } }],
    correctAnswer: 'kam' },
  { id: 'dk3-032', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'verbs',
    prompt: { de: 'Welche Zeitform ist "Er ging zur Schule"?', en: 'What tense is "Er ging zur Schule" (He went to school)?' },
    options: [{ value: 'präteritum', label: { de: 'Präteritum (Vergangenheit)', en: 'Preterite (past)' } }, { value: 'präsens', label: { de: 'Präsens (Gegenwart)', en: 'Present' } }, { value: 'perfekt', label: { de: 'Perfekt (Vergangenheit)', en: 'Perfect (past)' } }],
    correctAnswer: 'präteritum' },

  // --- Nouns: plurals ---
  { id: 'dk3-033', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Was ist die Mehrzahl von "Haus"?', en: 'What is the plural of "Haus" (house)?' },
    options: [{ value: 'Häuser', label: { de: 'Häuser', en: 'Häuser' } }, { value: 'Hause', label: { de: 'Hause', en: 'Hause' } }, { value: 'Hauser', label: { de: 'Hauser', en: 'Hauser' } }, { value: 'Häuse', label: { de: 'Häuse', en: 'Häuse' } }],
    correctAnswer: 'Häuser' },
  { id: 'dk3-034', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Was ist die Mehrzahl von "Baum"?', en: 'What is the plural of "Baum" (tree)?' },
    options: [{ value: 'Bäume', label: { de: 'Bäume', en: 'Bäume' } }, { value: 'Baumen', label: { de: 'Baumen', en: 'Baumen' } }, { value: 'Bäumer', label: { de: 'Bäumer', en: 'Bäumer' } }, { value: 'Baums', label: { de: 'Baums', en: 'Baums' } }],
    correctAnswer: 'Bäume' },
  { id: 'dk3-035', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'nouns',
    prompt: { de: 'Was ist die Mehrzahl von "Stuhl"?', en: 'What is the plural of "Stuhl" (chair)?' },
    options: [{ value: 'Stühle', label: { de: 'Stühle', en: 'Stühle' } }, { value: 'Stuhle', label: { de: 'Stuhle', en: 'Stuhle' } }, { value: 'Stühlen', label: { de: 'Stühlen', en: 'Stühlen' } }, { value: 'Stuhls', label: { de: 'Stuhls', en: 'Stuhls' } }],
    correctAnswer: 'Stühle' },

  // --- Sentences: word types ---
  { id: 'dk3-036', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'sentences',
    prompt: { de: 'Welches Wort ist ein Nomen (Namenwort)? "Der Hund läuft schnell."', en: 'Which word is a noun? "Der Hund läuft schnell." (The dog runs fast.)' },
    options: [{ value: 'Hund', label: { de: 'Hund', en: 'Hund (dog)' } }, { value: 'läuft', label: { de: 'läuft', en: 'läuft (runs)' } }, { value: 'schnell', label: { de: 'schnell', en: 'schnell (fast)' } }, { value: 'Der', label: { de: 'Der', en: 'Der (the)' } }],
    correctAnswer: 'Hund' },
  { id: 'dk3-037', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'sentences',
    prompt: { de: 'Welches Wort ist ein Verb (Tunwort)? "Die Katze schläft auf dem Sofa."', en: 'Which word is a verb? "Die Katze schläft auf dem Sofa." (The cat sleeps on the sofa.)' },
    options: [{ value: 'schläft', label: { de: 'schläft', en: 'schläft (sleeps)' } }, { value: 'Katze', label: { de: 'Katze', en: 'Katze (cat)' } }, { value: 'Sofa', label: { de: 'Sofa', en: 'Sofa (sofa)' } }, { value: 'auf', label: { de: 'auf', en: 'auf (on)' } }],
    correctAnswer: 'schläft' },

  // --- Prepositions ---
  { id: 'dk3-038', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'prepositions',
    prompt: { de: 'Welches Wort passt? Das Buch liegt ___ dem Tisch.', en: 'Which word fits? Das Buch liegt ___ dem Tisch. (The book is ___ the table.)' },
    options: [{ value: 'auf', label: { de: 'auf', en: 'auf (on)' } }, { value: 'aus', label: { de: 'aus', en: 'aus (out of)' } }, { value: 'mit', label: { de: 'mit', en: 'mit (with)' } }, { value: 'von', label: { de: 'von', en: 'von (from)' } }],
    correctAnswer: 'auf' },
  { id: 'dk3-039', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'prepositions',
    prompt: { de: 'Welches Wort passt? Die Katze sitzt ___ dem Stuhl.', en: 'Which word fits? Die Katze sitzt ___ dem Stuhl. (The cat sits ___ the chair.)' },
    options: [{ value: 'unter', label: { de: 'unter', en: 'unter (under)' } }, { value: 'über', label: { de: 'über', en: 'über (over)' } }, { value: 'aus', label: { de: 'aus', en: 'aus (out of)' } }, { value: 'mit', label: { de: 'mit', en: 'mit (with)' } }],
    correctAnswer: 'unter' },

  // --- True/False: grammar ---
  { id: 'dk3-040', type: 'true_false', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'nouns',
    prompt: { de: 'Alle Nomen (Namenwörter) werden im Deutschen großgeschrieben.', en: 'All nouns are capitalized in German.' },
    correctAnswer: true },
];
