import type { Question } from '../../../types/question';

export const deutschKlasse2: Question[] = [
  // === ORIGINAL 12 QUESTIONS (dk2-001 through dk2-012) ===
  { id: 'dk2-001', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Hund', en: 'Which article fits? ___ Hund (dog)' },
    options: [{ value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'der' },
  { id: 'dk2-002', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Katze', en: 'Which article fits? ___ Katze (cat)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-003', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Buch', en: 'Which article fits? ___ Buch (book)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-004', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Haus', en: 'Which article fits? ___ Haus (house)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-005', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Blume', en: 'Which article fits? ___ Blume (flower)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-006', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Welches Wort ist ein Nomen (Namenwort)?', en: 'Which word is a noun?' },
    options: [{ value: 'Tisch', label: { de: 'Tisch', en: 'Tisch (table)' } }, { value: 'laufen', label: { de: 'laufen', en: 'laufen (run)' } }, { value: 'schnell', label: { de: 'schnell', en: 'schnell (fast)' } }, { value: 'und', label: { de: 'und', en: 'und (and)' } }],
    correctAnswer: 'Tisch',
    explanation: { de: 'Nomen werden großgeschrieben!', en: 'Nouns are capitalized in German!' } },
  { id: 'dk2-007', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Schule', label: { de: 'Schule', en: 'Schule' } }, { value: 'Shule', label: { de: 'Shule', en: 'Shule' } }, { value: 'Schuhle', label: { de: 'Schuhle', en: 'Schuhle' } }, { value: 'Skule', label: { de: 'Skule', en: 'Skule' } }],
    correctAnswer: 'Schule' },
  { id: 'dk2-008', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Fahrrad', label: { de: 'Fahrrad', en: 'Fahrrad' } }, { value: 'Farat', label: { de: 'Farat', en: 'Farat' } }, { value: 'Farrad', label: { de: 'Farrad', en: 'Farrad' } }, { value: 'Fahrad', label: { de: 'Fahrad', en: 'Fahrad' } }],
    correctAnswer: 'Fahrrad' },
  { id: 'dk2-009', type: 'word_build', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Dort lernst du', en: 'Build the word: You learn there' },
    letters: ['S', 'C', 'H', 'U', 'L', 'E'],
    correctWord: 'SCHULE' },
  { id: 'dk2-010', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Fenster', en: 'Which article fits? ___ Fenster (window)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-011', type: 'drag_sort', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Sortiere die Wörter nach ihrem Artikel!', en: 'Sort the words by their article!' },
    items: [
      { id: 'hund', label: { de: 'Hund', en: 'Hund' } },
      { id: 'katze', label: { de: 'Katze', en: 'Katze' } },
      { id: 'kind', label: { de: 'Kind', en: 'Kind' } },
      { id: 'baum', label: { de: 'Baum', en: 'Baum' } },
    ],
    categories: [
      { id: 'der', label: { de: 'der', en: 'der' } },
      { id: 'die', label: { de: 'die', en: 'die' } },
      { id: 'das', label: { de: 'das', en: 'das' } },
    ],
    correctMapping: { hund: 'der', katze: 'die', kind: 'das', baum: 'der' } },
  { id: 'dk2-012', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'sentences',
    prompt: { de: 'Was steht am Ende eines Satzes?', en: 'What goes at the end of a sentence?' },
    options: [{ value: '.', label: { de: 'Punkt (.)', en: 'Period (.)' } }, { value: ',', label: { de: 'Komma (,)', en: 'Comma (,)' } }, { value: ':', label: { de: 'Doppelpunkt (:)', en: 'Colon (:)' } }, { value: '-', label: { de: 'Strich (-)', en: 'Dash (-)' } }],
    correctAnswer: '.' },

  // === NEW QUESTIONS (dk2-013 through dk2-048) ===

  // --- Articles (multiple_choice) ---
  { id: 'dk2-013', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Tisch', en: 'Which article fits? ___ Tisch (table)' },
    options: [{ value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'der' },
  { id: 'dk2-014', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Stuhl', en: 'Which article fits? ___ Stuhl (chair)' },
    options: [{ value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'der' },
  { id: 'dk2-015', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Ball', en: 'Which article fits? ___ Ball (ball)' },
    options: [{ value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'der' },
  { id: 'dk2-016', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Sonne', en: 'Which article fits? ___ Sonne (sun)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-017', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Schule', en: 'Which article fits? ___ Schule (school)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-018', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Mutter', en: 'Which article fits? ___ Mutter (mother)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-019', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Auto', en: 'Which article fits? ___ Auto (car)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-020', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Kind', en: 'Which article fits? ___ Kind (child)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-021', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Pferd', en: 'Which article fits? ___ Pferd (horse)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-022', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Vogel', en: 'Which article fits? ___ Vogel (bird)' },
    options: [{ value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'der' },
  { id: 'dk2-023', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Tür', en: 'Which article fits? ___ Tür (door)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-024', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Bett', en: 'Which article fits? ___ Bett (bed)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },
  { id: 'dk2-025', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Apfel', en: 'Which article fits? ___ Apfel (apple)' },
    options: [{ value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'der' },
  { id: 'dk2-026', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Hand', en: 'Which article fits? ___ Hand (hand)' },
    options: [{ value: 'die', label: { de: 'die', en: 'die' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'das', label: { de: 'das', en: 'das' } }],
    correctAnswer: 'die' },
  { id: 'dk2-027', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Welcher Artikel passt? ___ Glas', en: 'Which article fits? ___ Glas (glass)' },
    options: [{ value: 'das', label: { de: 'das', en: 'das' } }, { value: 'der', label: { de: 'der', en: 'der' } }, { value: 'die', label: { de: 'die', en: 'die' } }],
    correctAnswer: 'das' },

  // --- Nouns (multiple_choice) ---
  { id: 'dk2-028', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Welches Wort ist ein Nomen (Namenwort)?', en: 'Which word is a noun?' },
    options: [{ value: 'Baum', label: { de: 'Baum', en: 'Baum (tree)' } }, { value: 'rennen', label: { de: 'rennen', en: 'rennen (run)' } }, { value: 'groß', label: { de: 'groß', en: 'groß (big)' } }, { value: 'aber', label: { de: 'aber', en: 'aber (but)' } }],
    correctAnswer: 'Baum',
    explanation: { de: 'Nomen werden großgeschrieben!', en: 'Nouns are capitalized in German!' } },
  { id: 'dk2-029', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Welches Wort ist ein Nomen (Namenwort)?', en: 'Which word is a noun?' },
    options: [{ value: 'Vogel', label: { de: 'Vogel', en: 'Vogel (bird)' } }, { value: 'singen', label: { de: 'singen', en: 'singen (sing)' } }, { value: 'klein', label: { de: 'klein', en: 'klein (small)' } }, { value: 'oder', label: { de: 'oder', en: 'oder (or)' } }],
    correctAnswer: 'Vogel',
    explanation: { de: 'Nomen werden großgeschrieben!', en: 'Nouns are capitalized in German!' } },
  { id: 'dk2-030', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'nouns',
    prompt: { de: 'Welches Wort ist ein Nomen (Namenwort)?', en: 'Which word is a noun?' },
    options: [{ value: 'Fenster', label: { de: 'Fenster', en: 'Fenster (window)' } }, { value: 'spielen', label: { de: 'spielen', en: 'spielen (play)' } }, { value: 'lustig', label: { de: 'lustig', en: 'lustig (funny)' } }, { value: 'weil', label: { de: 'weil', en: 'weil (because)' } }],
    correctAnswer: 'Fenster',
    explanation: { de: 'Nomen werden großgeschrieben!', en: 'Nouns are capitalized in German!' } },

  // --- Spelling (multiple_choice) ---
  { id: 'dk2-031', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Kirche', label: { de: 'Kirche', en: 'Kirche' } }, { value: 'Kirsche', label: { de: 'Kirsche', en: 'Kirsche' } }, { value: 'Kirhe', label: { de: 'Kirhe', en: 'Kirhe' } }, { value: 'Kirce', label: { de: 'Kirce', en: 'Kirce' } }],
    correctAnswer: 'Kirche',
    explanation: { de: 'Kirche wird mit "ch" geschrieben.', en: 'Kirche (church) is spelled with "ch".' } },
  { id: 'dk2-032', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Brücke', label: { de: 'Brücke', en: 'Brücke' } }, { value: 'Brüke', label: { de: 'Brüke', en: 'Brüke' } }, { value: 'Brükke', label: { de: 'Brükke', en: 'Brükke' } }, { value: 'Brüce', label: { de: 'Brüce', en: 'Brüce' } }],
    correctAnswer: 'Brücke',
    explanation: { de: 'Nach einem kurzen Vokal kommt "ck".', en: 'After a short vowel comes "ck".' } },
  { id: 'dk2-033', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Katze', label: { de: 'Katze', en: 'Katze' } }, { value: 'Kaze', label: { de: 'Kaze', en: 'Kaze' } }, { value: 'Kazze', label: { de: 'Kazze', en: 'Kazze' } }, { value: 'Katse', label: { de: 'Katse', en: 'Katse' } }],
    correctAnswer: 'Katze',
    explanation: { de: 'Nach einem kurzen Vokal kommt "tz".', en: 'After a short vowel comes "tz".' } },
  { id: 'dk2-034', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Spiegel', label: { de: 'Spiegel', en: 'Spiegel' } }, { value: 'Spigel', label: { de: 'Spigel', en: 'Spigel' } }, { value: 'Schpiegel', label: { de: 'Schpiegel', en: 'Schpiegel' } }, { value: 'Spegel', label: { de: 'Spegel', en: 'Spegel' } }],
    correctAnswer: 'Spiegel',
    explanation: { de: 'Spiegel wird mit "ie" geschrieben.', en: 'Spiegel (mirror) is spelled with "ie".' } },
  { id: 'dk2-035', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Welches Wort ist richtig geschrieben?', en: 'Which word is spelled correctly?' },
    options: [{ value: 'Schmetterling', label: { de: 'Schmetterling', en: 'Schmetterling' } }, { value: 'Shmetterling', label: { de: 'Shmetterling', en: 'Shmetterling' } }, { value: 'Schmeteling', label: { de: 'Schmeteling', en: 'Schmeteling' } }, { value: 'Schmeterling', label: { de: 'Schmeterling', en: 'Schmeterling' } }],
    correctAnswer: 'Schmetterling',
    explanation: { de: 'Schmetterling hat ein doppeltes "t".', en: 'Schmetterling (butterfly) has a double "t".' } },

  // --- Sentences (multiple_choice) ---
  { id: 'dk2-036', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'sentences',
    prompt: { de: 'Welcher Satz ist richtig?', en: 'Which sentence is correct?' },
    options: [{ value: 'Die Sonne scheint.', label: { de: 'Die Sonne scheint.', en: 'Die Sonne scheint.' } }, { value: 'die Sonne scheint.', label: { de: 'die Sonne scheint.', en: 'die Sonne scheint.' } }, { value: 'Die Sonne scheint', label: { de: 'Die Sonne scheint', en: 'Die Sonne scheint' } }, { value: 'die sonne scheint.', label: { de: 'die sonne scheint.', en: 'die sonne scheint.' } }],
    correctAnswer: 'Die Sonne scheint.',
    explanation: { de: 'Ein Satz beginnt mit einem Großbuchstaben und endet mit einem Punkt.', en: 'A sentence starts with a capital letter and ends with a period.' } },
  { id: 'dk2-037', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'sentences',
    prompt: { de: 'Was steht am Ende einer Frage?', en: 'What goes at the end of a question?' },
    options: [{ value: '?', label: { de: 'Fragezeichen (?)', en: 'Question mark (?)' } }, { value: '.', label: { de: 'Punkt (.)', en: 'Period (.)' } }, { value: '!', label: { de: 'Ausrufezeichen (!)', en: 'Exclamation mark (!)' } }, { value: ',', label: { de: 'Komma (,)', en: 'Comma (,)' } }],
    correctAnswer: '?' },
  { id: 'dk2-038', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'sentences',
    prompt: { de: 'Was steht am Ende eines Ausrufs? (z.B. "Hilfe")', en: 'What goes at the end of an exclamation? (e.g. "Help")' },
    options: [{ value: '!', label: { de: 'Ausrufezeichen (!)', en: 'Exclamation mark (!)' } }, { value: '.', label: { de: 'Punkt (.)', en: 'Period (.)' } }, { value: '?', label: { de: 'Fragezeichen (?)', en: 'Question mark (?)' } }, { value: ',', label: { de: 'Komma (,)', en: 'Comma (,)' } }],
    correctAnswer: '!' },

  // --- Word Build ---
  { id: 'dk2-039', type: 'word_build', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Ein guter Kamerad', en: 'Build the word: A good buddy' },
    letters: ['F', 'R', 'E', 'U', 'N', 'D'],
    correctWord: 'FREUND' },
  { id: 'dk2-040', type: 'word_build', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Man trinkt es', en: 'Build the word: You drink it' },
    letters: ['W', 'A', 'S', 'S', 'E', 'R'],
    correctWord: 'WASSER' },
  { id: 'dk2-041', type: 'word_build', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Mehr als ein Kind', en: 'Build the word: More than one child' },
    letters: ['K', 'I', 'N', 'D', 'E', 'R'],
    correctWord: 'KINDER' },
  { id: 'dk2-042', type: 'word_build', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'spelling',
    prompt: { de: 'Baue das Wort: Das macht man mit einem Ball', en: 'Build the word: What you do with a ball' },
    letters: ['S', 'P', 'I', 'E', 'L', 'E', 'N'],
    correctWord: 'SPIELEN' },

  // --- Drag Sort ---
  { id: 'dk2-043', type: 'drag_sort', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'articles',
    prompt: { de: 'Sortiere die Wörter nach ihrem Artikel!', en: 'Sort the words by their article!' },
    items: [
      { id: 'tisch', label: { de: 'Tisch', en: 'Tisch' } },
      { id: 'sonne', label: { de: 'Sonne', en: 'Sonne' } },
      { id: 'auto', label: { de: 'Auto', en: 'Auto' } },
      { id: 'blume', label: { de: 'Blume', en: 'Blume' } },
    ],
    categories: [
      { id: 'der', label: { de: 'der', en: 'der' } },
      { id: 'die', label: { de: 'die', en: 'die' } },
      { id: 'das', label: { de: 'das', en: 'das' } },
    ],
    correctMapping: { tisch: 'der', sonne: 'die', auto: 'das', blume: 'die' } },
  { id: 'dk2-044', type: 'drag_sort', subject: 'deutsch', klasse: 2, difficulty: 2, topic: 'nouns',
    prompt: { de: 'Sortiere: Was ist ein Nomen, was ist ein Verb?', en: 'Sort: Which is a noun, which is a verb?' },
    items: [
      { id: 'hund', label: { de: 'Hund', en: 'Hund' } },
      { id: 'laufen', label: { de: 'laufen', en: 'laufen' } },
      { id: 'schule', label: { de: 'Schule', en: 'Schule' } },
      { id: 'spielen', label: { de: 'spielen', en: 'spielen' } },
    ],
    categories: [
      { id: 'nomen', label: { de: 'Nomen', en: 'Noun' } },
      { id: 'verb', label: { de: 'Verb', en: 'Verb' } },
    ],
    correctMapping: { hund: 'nomen', laufen: 'verb', schule: 'nomen', spielen: 'verb' } },

  // --- True/False ---
  { id: 'dk2-045', type: 'true_false', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'nouns',
    prompt: { de: '"Hund" ist ein Nomen (Namenwort).', en: '"Hund" (dog) is a noun.' },
    correctAnswer: true,
    explanation: { de: 'Hund ist ein Nomen. Nomen werden großgeschrieben.', en: 'Hund is a noun. Nouns are capitalized in German.' } },
  { id: 'dk2-046', type: 'true_false', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'nouns',
    prompt: { de: '"laufen" ist ein Nomen (Namenwort).', en: '"laufen" (to run) is a noun.' },
    correctAnswer: false,
    explanation: { de: 'laufen ist ein Verb (Tunwort), kein Nomen.', en: 'laufen is a verb, not a noun.' } },

  // --- Plurals (multiple_choice) ---
  { id: 'dk2-047', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'plurals',
    prompt: { de: 'Was ist die Mehrzahl von "Hund"?', en: 'What is the plural of "Hund" (dog)?' },
    options: [{ value: 'Hunde', label: { de: 'Hunde', en: 'Hunde' } }, { value: 'Hunden', label: { de: 'Hunden', en: 'Hunden' } }, { value: 'Hünde', label: { de: 'Hünde', en: 'Hünde' } }, { value: 'Hundes', label: { de: 'Hundes', en: 'Hundes' } }],
    correctAnswer: 'Hunde' },
  { id: 'dk2-048', type: 'multiple_choice', subject: 'deutsch', klasse: 2, difficulty: 1, topic: 'plurals',
    prompt: { de: 'Was ist die Mehrzahl von "Katze"?', en: 'What is the plural of "Katze" (cat)?' },
    options: [{ value: 'Katzen', label: { de: 'Katzen', en: 'Katzen' } }, { value: 'Katze', label: { de: 'Katze', en: 'Katze' } }, { value: 'Kätzchen', label: { de: 'Kätzchen', en: 'Kätzchen' } }, { value: 'Katzes', label: { de: 'Katzes', en: 'Katzes' } }],
    correctAnswer: 'Katzen' },
];
