import type { Question } from '../../../types/question';

export const deutschKlasse3: Question[] = [
  { id: 'dk3-001', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "groß"?', en: 'What is the opposite of "groß" (big)?' },
    options: [{ value: 'klein', label: { de: 'klein', en: 'klein (small)' } }, { value: 'lang', label: { de: 'lang', en: 'lang (long)' } }, { value: 'dick', label: { de: 'dick', en: 'dick (thick)' } }, { value: 'alt', label: { de: 'alt', en: 'alt (old)' } }],
    correctAnswer: 'klein' },
  { id: 'dk3-002', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "heiß"?', en: 'What is the opposite of "heiß" (hot)?' },
    options: [{ value: 'kalt', label: { de: 'kalt', en: 'kalt (cold)' } }, { value: 'warm', label: { de: 'warm', en: 'warm (warm)' } }, { value: 'nass', label: { de: 'nass', en: 'nass (wet)' } }, { value: 'trocken', label: { de: 'trocken', en: 'trocken (dry)' } }],
    correctAnswer: 'kalt' },
  { id: 'dk3-003', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Welches zusammengesetzte Wort ist richtig?', en: 'Which compound word is correct?' },
    options: [{ value: 'Haustür', label: { de: 'Haustür', en: 'Haustür (front door)' } }, { value: 'HausTür', label: { de: 'HausTür', en: 'HausTür' } }, { value: 'Haus Tür', label: { de: 'Haus Tür', en: 'Haus Tür' } }, { value: 'haustur', label: { de: 'haustur', en: 'haustur' } }],
    correctAnswer: 'Haustür' },
  { id: 'dk3-004', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Was ergibt "Schul" + "tasche"?', en: 'What does "Schul" + "tasche" make?' },
    options: [{ value: 'Schultasche', label: { de: 'Schultasche', en: 'Schultasche (school bag)' } }, { value: 'SchulTasche', label: { de: 'SchulTasche', en: 'SchulTasche' } }, { value: 'Schulltasche', label: { de: 'Schulltasche', en: 'Schulltasche' } }],
    correctAnswer: 'Schultasche' },
  { id: 'dk3-005', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Ich ___ schnell.', en: 'Which form is correct? Ich ___ schnell. (I ___ fast.)' },
    options: [{ value: 'laufe', label: { de: 'laufe', en: 'laufe' } }, { value: 'laufst', label: { de: 'laufst', en: 'laufst' } }, { value: 'lauft', label: { de: 'lauft', en: 'lauft' } }, { value: 'laufen', label: { de: 'laufen', en: 'laufen' } }],
    correctAnswer: 'laufe' },
  { id: 'dk3-006', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'verbs',
    prompt: { de: 'Welche Form ist richtig? Er ___ ein Buch.', en: 'Which form is correct? Er ___ ein Buch. (He ___ a book.)' },
    options: [{ value: 'liest', label: { de: 'liest', en: 'liest' } }, { value: 'lest', label: { de: 'lest', en: 'lest' } }, { value: 'lese', label: { de: 'lese', en: 'lese' } }, { value: 'lesen', label: { de: 'lesen', en: 'lesen' } }],
    correctAnswer: 'liest' },
  { id: 'dk3-007', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'adjectives',
    prompt: { de: 'Was ist das Gegenteil von "leise"?', en: 'What is the opposite of "leise" (quiet)?' },
    options: [{ value: 'laut', label: { de: 'laut', en: 'laut (loud)' } }, { value: 'schnell', label: { de: 'schnell', en: 'schnell (fast)' } }, { value: 'dunkel', label: { de: 'dunkel', en: 'dunkel (dark)' } }, { value: 'hell', label: { de: 'hell', en: 'hell (bright)' } }],
    correctAnswer: 'laut' },
  { id: 'dk3-008', type: 'word_build', subject: 'deutsch', klasse: 3, difficulty: 2, topic: 'compound_words',
    prompt: { de: 'Baue das Wort: Tasche für die Schule', en: 'Build the word: bag for school' },
    letters: ['S', 'C', 'H', 'U', 'L', 'T', 'A', 'S', 'C', 'H', 'E'],
    correctWord: 'SCHULTASCHE' },
  { id: 'dk3-009', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 3, topic: 'verbs',
    prompt: { de: 'Welche Zeitform ist "Ich habe gespielt"?', en: 'What tense is "Ich habe gespielt" (I have played)?' },
    options: [{ value: 'perfekt', label: { de: 'Perfekt (Vergangenheit)', en: 'Perfect (past)' } }, { value: 'präsens', label: { de: 'Präsens (Gegenwart)', en: 'Present' } }, { value: 'futur', label: { de: 'Futur (Zukunft)', en: 'Future' } }],
    correctAnswer: 'perfekt' },
  { id: 'dk3-010', type: 'multiple_choice', subject: 'deutsch', klasse: 3, difficulty: 1, topic: 'nouns',
    prompt: { de: 'Was ist die Mehrzahl von "Kind"?', en: 'What is the plural of "Kind" (child)?' },
    options: [{ value: 'Kinder', label: { de: 'Kinder', en: 'Kinder' } }, { value: 'Kinds', label: { de: 'Kinds', en: 'Kinds' } }, { value: 'Kindern', label: { de: 'Kindern', en: 'Kindern' } }, { value: 'Kindere', label: { de: 'Kindere', en: 'Kindere' } }],
    correctAnswer: 'Kinder' },
];
